### ISSUE TITLE
Compile commandline version on macOS?

### ISSUE THREAD

**Issue by luckman212** [nu-book/zxing-cpp#112]
This looks like the de-facto project for zxing now. I was able to build a working CLI binary from [glassechidna/zxing-cpp](https://github.com/glassechidna/zxing-cpp) and I am also able to complete the `make` script from this project based on the 1.0.7 release, but I can't find a binary anywhere.

Is there a way to build a commandline target?

**Comment by huycn** [comment]
You may want to point your SOURCE in CMake to "example" instead. The CMakeLists.txt file there will build an executable.

**Comment by luckman212** [comment]
**Wonderful!** 🙌
Thank you for this.
For anyone else who needs a nudge in the right direction:

```
cd example
cmake . && make
for b in *_image ; do cp $b /usr/local/bin/ ; done
generate_image -size 128x128 -margin 1 QR_CODE 'https://github.com/nu-book/zxing-cpp' qrtest.png
scan_image qrtest.png
```

**Comment by luckman212** [comment]
In case anyone comes here looking for macOS build instructions, they are easier now since the 1.2.0 release:

```

cd zxing-cpp-1.2.0
cmake .
make
cd example
./ZXingWriter -size 128x128 -margin 1 QR_CODE 'https://github.com/nu-book/zxing-cpp' qrtest.png
./ZXingReader qrtest.png
```
