### ISSUE TITLE
ImageData is throwing an exception via wasm wrapper

### ISSUE THREAD

**Issue by pakizito** [nu-book/zxing-cpp#114]
Hi,
I have an ImageData as a source image and I always get an:
result: {"format":"","text":"","error":"Error loading image"}

I tried multiple ways to get the array from the image but always get this error.

const data = new Uint8Array(image.data.buffer); (or simply image.data or image.data.buffer)
const buffer = zxing._malloc(data.length);
...

none of them seems to be working...

Does anyone have an idea of what this could be?

Thanks!

**Comment by huycn** [comment]
What kind of object is your "ImageData"?
Your image is in which format? e.g. png, jpeg?

For sample code, you can have a look here:
https://github.com/nu-book/zxing-cpp/blob/gh-pages/demo_reader.html#L10-L25
You can try to replace `evt.target.result` with your `image.data.buffer`, see if that will work for you.

**Comment by pakizito** [comment]
Hi Huycn,
I did try that and get the error.
I get the image from the canvas (html element) which is a copy of the video stream from a webcam for example, in this case is from my built-in camera of the laptop.
I get the ImageData from the ctx.getImageData from the canvas.getContext("2d").

Thank you very much for your quick reply.

**Comment by huycn** [comment]
The error was that wasm wrapper does not support raw pixels but only formated image data (png, jpeg, etc.). I have added a new method for this:
```
readBarcodeFromPixmap(buffer: BufferSource, imgWidth: number, imgHeight: number, tryHarder: boolean, format: string)
```
You can see example here: https://github.com/nu-book/zxing-cpp/blob/gh-pages/zxing_viddemo.html#L30

**Comment by pakizito** [comment]
Wow :) amazing.. works perfectly!
I think a good addon to the result would the getResultPoints() of the result. Would that be a possibility?

Thank you very much for such an amazing fast reply and fix!
