### ISSUE TITLE
zxing gstreamer plugin available

### ISSUE THREAD

**Issue by dabrain34** [nu-book/zxing-cpp#118]
Here is a zxing plugin for GStreamer > 1.17.

https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/merge_requests/743

https://gitlab.freedesktop.org/gstreamer/cerbero/merge_requests/287

**Comment by axxel** [comment]
Thanks for spreading the word and letting us know! :). How is it going with your plugin, any success stories?

Since there seems to be nothing to be done here from our side, we can close the issue, right?

**Comment by dabrain34** [comment]
except my pet project, nothing more but I hope it can help to spread your job.
Yes we can close the issue.
