### ISSUE TITLE
Command line tools

### ISSUE THREAD

**Issue by matheusmoreira** [nu-book/zxing-cpp#119]
[The ZBar project] offers the `zbarimg` and `zbarcam` programs. It'd be awesome if this project had `zximg` and `zxcam` programs as well.

[The `scan_image` program][scan_image] is pretty good already, even though it was meant to be just an example. Are you open to making it part of the official build and distribution packages after improvements? I'd like to add some features, binary decoding for example. I've also been working on a camera program with a V4L2 backend.

[The ZBar project]: https://github.com/mchehab/zbar
[scan_image]: https://github.com/nu-book/zxing-cpp/blob/master/example/scan_image.cpp

**Comment by huycn** [comment]
Yes that is a great idea. I will be happy to merge your PRs.

**Comment by axxel** [comment]
If you are still pursuing this effort: I recently did a bit of naming 'cleanup'. The samples are now called `ZXingReader` and `ZXingWriter` and are good to be added to distributions.

Also, note that @swex has a Qt wrapper with a sample program that probably does something along the lines of zxcam.

**Comment by axxel** [comment]
Closed for lack of feedback.
