### ISSUE TITLE
 C2039

### ISSUE THREAD

**Issue by 15991711351** [nu-book/zxing-cpp#12]
Class "Gdiplus: : Bitmap" has no members "ConvertFormat"

**Comment by huycn** [comment]
ConvertFormat() method is defined only when version 1.1 of GdiPlus is "enabled", which is done in test/runners/gdiplus/CMakeLists.txt with the flag -DGDIPVER=0x0110.

Did you use the folder test/runners/gdiplus as your "Source Code" in CMake? If yes, check properties of your project: among preprocessor definitions, one should find GDIPVER=0x0110.
If you don't use that folder as your main source code, just add that to your project preprocessor definitions.

**Comment by 15991711351** [comment]
谢谢
