### ISSUE TITLE
Library presence in Linux distributions

### ISSUE THREAD

**Issue by hosiet** [nu-book/zxing-cpp#120]
Hi, I'm writing to let you know the presence of zxing-cpp in some Linux distributions.

* Arch Linux: https://www.archlinux.org/packages/extra/x86_64/zxing-cpp/
* Debian: https://tracker.debian.org/pkg/zxing-cpp
* Ubuntu (since 20.04 LTS): https://launchpad.net/ubuntu/+source/zxing-cpp

Feel free to get into contact with distribution package maintainers if coordination is needed.

**Comment by huycn** [comment]
@hosiet 
That's great!
Thank you.
