### ISSUE TITLE
No relocatable cmake setup

### ISSUE THREAD

**Issue by stefanbuettner** [nu-book/zxing-cpp#123]
Hey there,

the includes of `ZXing::Core` are not defined in a relocatable manner.

[core/CMakeLists.cpp:443](https://github.com/nu-book/zxing-cpp/blob/master/core/CMakeLists.txt#L443) is
```cmake
441 target_include_directories (ZXingCore
442     PUBLIC "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/src>"
443     INTERFACE "$<INSTALL_INTERFACE:${CMAKE_INSTALL_PREFIX}/include>"
444 )
```

According to [cmake's creating relocatable packages](https://cmake.org/cmake/help/v3.3/manual/cmake-packages.7.html#creating-relocatable-packages) it should be
```cmake
441 target_include_directories (ZXingCore
442     PUBLIC "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/src>"
443     INTERFACE "$<INSTALL_INTERFACE:include>"
444 )
```

Cheers,
Stefan

**Comment by huycn** [comment]
Fixed. Thanks!
