### ISSUE TITLE
vactor subscript out of range?

### ISSUE THREAD

**Issue by 15991711351** [nu-book/zxing-cpp#13]
```
	std::wstring c = L"ABC" ;
	ZXing::BitMatrix mar(100);
	ZXing::QRCode::Writer writerQR;
	writerQR.setEncoding(ZXing::CharacterSet::UTF8);
	writerQR.encode( c, 100, 100, mar);

```
![eeeeeeeeeeee](https://cloud.githubusercontent.com/assets/10155058/26720084/70585fa2-47b9-11e7-9480-08b29e157b7f.png)

![eor](https://cloud.githubusercontent.com/assets/10155058/26719961/08837e66-47b9-11e7-87ce-83ca3e87bbe3.png)

How can you make a qr code?

**Comment by huycn** [comment]
Thank you for reporting this issue.
I've just committed a fix for this error and another bug in QRCode writer. It should work by now.
