### ISSUE TITLE
Improve / redefine Result::resultPoints

### ISSUE THREAD

**Issue by axxel** [nu-book/zxing-cpp#130]
I'd like to propose a change regarding the `Result::resultPoints` contents and name. Currently the contents of this `std::vector` is basically undefined. The documentation says it contains points of interest like e.g. the position of detection markers. So the number of points in this array and their meaning change from barcode format to barcode format.

I assume that almost no one makes use of this information and if so, they assume the points form a convex [quadrilateral](https://en.wikipedia.org/wiki/Quadrilateral) which contains the area of the barcode. That is e.g. true for the DataMatrix reader but not quite for the QRCode reader and apparently [not at all](https://github.com/nu-book/zxing-cpp/issues/105#issuecomment-595299420) for the PDF417 reader. In the 1D case the behavior is also inconsistent across the different formats.

I suggest to deprecate this member and instead introduce a new one called `Result::position`. And this should provide a struct containing excatly 4 2D points describing the above mentioned quadrilateral. The struct should have a means to identify which point is which, like `Point topLeft()`, etc. methods.

An open question for me is whether those points should contain int or float coordinates. There is potentially sub-pixel precision information available but I highly doubt their usefulness on the client side. And they have the downside that you would need to communicate and understand
  1. what exactly a position of e.g. (0.5, 0.5) means (center or corner of the first pixel)
  2. what exactly the position of each corner means (center of the first pixel of the barcode or edge 
between background and barcode)

To make it most strait forward and user friendly, I'd go for integer precision and have it mean "the quadrilateral that covers all the area that went into the reading of this code". For 1D codes this will mean it contains only one line.

Again, I'm not interested in creating more problems than solving, so if @huycn, @vkrause, @bimusiek or others have any feedback, please let me know.

**Comment by vkrause** [comment]
We aren't using that feature at all AFAIK, but the proposed changes sound reasonable to me.
