### ISSUE TITLE
Rotation not set when detecting DataMatrix

### ISSUE THREAD

**Issue by GregoryHMVV** [nu-book/zxing-cpp#134]
It seems that currently only 1D codes set the rotation metadata during barcode detection. I would imagine that it's not extremely hard to do this for datamatrix as well, as the top right cell in an unrotated code is always white.

**Comment by axxel** [comment]
That is correct. There is one fundamental difference between 1D and 2D codes though: the latter can have an arbitrary rotation (at least the QR and the datamatrix codes), while the 1D codes have to be sufficiently leveled to be detected at all. (There has to be a single image row or column that passes through the whole code.) This means the 1D codes are by definition approximately either 0°, 90°, 180° or 270°. The datamatrix codes can have any angle.

As a result I see 3 potential ways to get some meaningful orientation information:
1. an approximation by quadrant as for the 1D codes
1. an angle of maybe the center-line relative to the top edge of the image
1. a defined set of top-left/top-right/etc. positions of the 4 corners (see also #130)

I'd argue that number 3 is the way to go, as it contains all information there is about location and orientation.

What is it that you want to do with this information in this particular context (datamatrix)?

**Comment by GregoryHMVV** [comment]
I'm using zxing to read a datamatrix and replacing it with a datamatrix with different parameters. Customers don't like it when the orientation changes during that process. I've written some code to detect the orientation afterwards (I work on vector data so that code unfortunately can't be put into zxing) but it would be nice if I got the rotation information out of zxing.

I would of course prefer to be able to use the same calls to retrieve the orientation for all types of barcodes. Unless I'm mistaken the orientation in the metadata is an integer representing the angle in degrees, so even an arbitrary angle could be stored there (as you're working on pixel data the 1 degree granularity is probably on par with (or even higher than) the precision on low res images ).

I don't know enough about the zxing internals to say which of the proposed ways is the more appropriate. I feel that 2 might be the easiest to use from a user perspective.

**Comment by axxel** [comment]
So you are only dealing with 'pure' codes? Meaning your input contains nothing but a perfectly aligned barcode and you know where it is but you don't know in advance which of the 4 possible orientations it has?

Thinking of 2) vs 3): in fact, 2) could be a method of the `Result` struct that calculates the angle from the position information. Having it stored in this cumbersome metadata map is not the canonical place anyway as soon as all codes provide this information.

**Comment by GregoryHMVV** [comment]
Our vector input is far from pure... There's a rather complicated prepass that goes over the vector data to isolate parts that are possibly barcodes and those parts are then rendered and passed to zxing. 
I don't have a preference for 2 over 3; I would just really like it to be the same method for all barcodes. Currently we use the metadata as that's the only one I knew about. If after a zxing update that changes to something else that's perfectly fine with me (as if I had a say in it ;-) )provided I don't have to use a different method for every type of barcode.

**Comment by axxel** [comment]
Note: the changes I just committed are not thoroughly tested, yet. Please let me know if there are issues result of that new code.
