### ISSUE TITLE
Any advice for an ARM porting?

### ISSUE THREAD

**Issue by gbmbg** [nu-book/zxing-cpp#135]
Good morning everybody.
I found your cpp porting very useful. However, I am looking for lighter implementation since I must embed it into an STM32 MCU.
I come across to this project:
https://github.com/tachcard/arm-barcode-scanner
Interesting indeed but based on an old cpp porting of zxing. I also explored the Zbar approach in pure C but it has the same memory issues, so I am seriously thinking if would be a good idea to try an arm porting myself...
Do you think it is a good idea? Am I reinventing the wheel? If not, do you have any advice to tailor your library into an MCU? 
As you can imagine I need to optimize memory allocation and possibly avoid threading computation since using an OS is another layer of complexity involving more computational resources.
I know I am asking a lot. But any advice on a starting point would be very appreciated.
Thanks a lot, and work well.

**Comment by axxel** [comment]
I see no reason why this code could not be made to run on your ARM platform. To answer whether or not the current approach is generally feasible with your memory limitations, I'd need to know your memory limitations :).

1. what kind of barcodes do you want to detect (there is a substantial difference between the individual formats, especially between 1D and 2D codes)?
1. how big is your input in pixels?
1. how much spare heap memory do you have?

Note: there is (basically) no threading/concurrency code present at the moment.

**Comment by huycn** [comment]
I believe the questions of axxel above are very important. Current code is already running on ARM (for both Android and Windows UWP builds), and from our experiences, the memory consumption of the readers themselves are far behind the memory buffers used to manipulate input images. The CPU time used to parsing barcodes is significant or not depends all on how many barcodes to expect to scan, and can easily optimized. Thus, IMHO, you are not going get a lot by going to the vanilla C. There are also options to turnoff RTTI and Exceptions, which are sometimes not available for size limited implementations of STL.

**Comment by gbmbg** [comment]
Thanks a lot for your quick answers. Here are my constrains:
1. Well for now we could start from just 1D barcode 
2. RGB888 640*360 px 
3. at last 3 Mb 
Answering your note:
Sorry I found the "once_flag" inside the binarizers which can be implemented with mutex inside the OS, if I am right, so I thought to the multithreading.
Concerning the Huycn comment if I understand well I can exclude these functionalities with the right parameters during the compilation process?
Thanks a lot for your help

**Comment by axxel** [comment]
1. Very good, if you could additionally limit yourself to not use the "tryRotate" hint, then the code needs no copy of your binarized image.
2. if you could make sure to convert that to grayscale (potentially in-place) before handing it over, then current code does not copy your image buffer at all.
3. that is indeed not a lot of memory but should be sufficient. That said, I have no hard measurements of how much memory is currently being used. It is likely a good idea to add some more fine-grained "enable format_x" build options to at least get rid of the 2D codes.

As for the "once_flag" that is present but can easily be defined out. Actually, I cannot tell right now why @huycn added that in the first place. Having one `LuminanceSouce` and then start multiple threads accessing that through multiple `MultiFormatReader`s in parallel?

**Comment by gbmbg** [comment]
1 Well I would prefer to maintain the “try rotate” feature, it is very useful for me
2 Agree with you with grayscale conversion in place (just one byte per pixel would be sufficient, right?)
3 ok thanks I will add only the 1D formats in my build
I will wait for @huycn  answer and I have already defined out the once_flag, hoping not to breake the code.
Thanks again

**Comment by huycn** [comment]
@axxel's guess was right. The "once_flag" was to share same LuminanceSource instance in multiple readers running in parallels for real-time detection. Thus, if you are not running multiple threads, just can just defined out as he suggested. Or if you know if are going to need to whole matrix anyway (for 2D readers), you can also remove the line `call_once` and call `InitBlackMatrix()` in constructor. The "cache" (and hence once_flag) was there is to make sure we pay only for what it's used.

**Comment by gbmbg** [comment]
Ok thanks a lot! 
I will try with this approach and let you know.

**Comment by axxel** [comment]
Any progress/success you'd like to share? We'd gladly improve the out-of-the-box experience for embedded systems if possible and useful.

**Comment by gbmbg** [comment]
Well, I am trying, but for now I got no progress. I will let you know hopefully by the end of this week. Thanks for your interest.

**Comment by gbmbg** [comment]
Hi there!
So, I finally found time to focus on this problem.
I followed your advice: now I am using an Image of type Lum and giving it to the readbarcode function, but I got a memory problem since it makes a copy and I am running out of heap. 
I am not using tryrotate nor tryharder. 
Is this copy necessary if I choose to look for just one type of barcode at time? 
Any advice to exclude it without braking everything? 
I think that if I am able to overcome this memory problem maybe the binarizer will work since it is not using so much heap, am I right?
Thanks for your kind help

**Comment by axxel** [comment]
You are right, contrary to my earlier claim, even when passed a Lum buffer with no rotation the code makes a copy of the complete frame (which it would not really have to). That said, a 640x350 frame uses 224kB. You wrote you had 3MB spare, so if you can not store two of those frames at one time, something does not add up. If you use the 2D decoders you'll need another copy for the binarized output. (Or at least an 8th but that code path might not fully work at the moment).

I could make sure the one copy in the `GenericLuminanceSource` goes away but if it would then just fail in the binarizer anyway, it would not make a difference, right?

**Comment by gbmbg** [comment]
Thanks @axxel.
To be honest I have 3 Mb RAM of free space but it is in an external  8 Mb SRAM. My total heap works inside a 512 KB RAM. So I got my RGB (640x360x3) frame than process it to grayscale (640x360) on external SRAM. 
So with 372 KB of free heap when the code makes a copy I am pretty out of resources (yes there is other stuff running and I have already tried to reduce memory consumption).
The only way, in my opinion, is storing the various copies on external SRAM or try to allocate part of the heap outside it but I think that will be a huge effort changing everything inside you library.
What do you think? Thanks again

**Comment by axxel** [comment]
I see 2 options at the moment:

 1) get rid of the unnecessary copy and make sure the (slower/old) packed BitMatrix code still works and it might barely fit. But as I said, I don't have a clean picture of where and how much memory is allocated. Maybe there is another bottle-neck.
 2) provide a hack to make the code get it's 'huge' allocations via a custom `malloc`.

You could experiment with 2) by coming up with your own `std::allocator` implementation and hack that into the `std::vector` inside `ByteArray` and `BitMatrix`. That might actually be not too invasive and do the trick.

**Comment by gbmbg** [comment]
Ok I will try both options starting from the second one since I would like to mantain a forward compatibility.
 I'll let you know. Thanks a lot!

**Comment by axxel** [comment]
Any update on your efforts?

**Comment by axxel** [comment]
Closed for lack of feedback. We'll reopen in case this should get picked up again by the OP.

**Comment by gbmbg** [comment]
> Any update on your efforts?

Sorry I did not see your question. For now, the project is in stand-by. Maybe I found a way to resolve this issue but I have no time now to work on it, I will let you know.
