### ISSUE TITLE
a small rotating degree ruins qrcode decoding

### ISSUE THREAD

**Issue by DuckSoft** [nu-book/zxing-cpp#142]
![图片](https://user-images.githubusercontent.com/7822648/87122397-622ad780-c2b7-11ea-96bb-117d9619c1d0.png)

Tested with both [official demo](https://nu-book.github.io/zxing-cpp/demo_reader.html) and compiled version, with tryHarder and tryRotate on.

![图片](https://user-images.githubusercontent.com/7822648/87122863-4411a700-c2b8-11ea-86aa-0dcc6dc3ead1.png)
After rotating this image by 2deg, both official demo and compiled version can now decode correctly.

**Comment by axxel** [comment]
Just to give you little feedback: This will be fixed as part of an upcoming reimplementation of the QRDetector.

**Comment by axxel** [comment]
Picking up on this: is it ok if we include your sample into the set of testing images?

**Comment by DuckSoft** [comment]
> Picking up on this: is it ok if we include your sample into the set of testing images?

Sure. Use it freely.
