### ISSUE TITLE
“initializer list”can not transform to“ZXing::BarAndSpace<ZXing::PatternView::value_type>”

### ISSUE THREAD

**Issue by tigerdhl** [nu-book/zxing-cpp#144]
hi, when I done the cmake, I build the project ZXing, but found this error in the file  "ODRowReader.h",  I build it with vs2015 in windows. do you know what is the problem?

**Comment by tigerdhl** [comment]
and also when I cmake in the path "../wrappers/gdiplus",  I build the project ZXingGdiPlus, still found the problem like this “initializer list”can not transform to“ZXing::BarAndSpace<ZXing::PatternView::value_type>”

**Comment by axxel** [comment]
Could you please post the complete message from the compiler regarding this specific line? (typically a couple lines of output from the compiler explaining the issue for one line of source code.)

**Comment by tigerdhl** [comment]
> Could you please post the complete message from the compiler regarding this specific line? (typically a couple lines of output from the compiler explaining the issue for one line of source code.)

the problem descrip this “initializer list”can not transform to“ZXing::BarAndSpace<ZXing::PatternView::value_type>”
and I found the problem come from function of the file  "ODRowReader.h" follows:

static BarAndSpaceI NarrowWideThreshold(const PatternView& view)
	{
		BarAndSpaceI m = { **std::numeric_limits<BarAndSpaceI::value_type>::max(),std::numeric_limits<BarAndSpaceI::value_type>::max()};
		BarAndSpaceI M = {0, 0};**
		for (int i = 0; i < view.size(); ++i) {
			m[i] = std::min(m[i], view[i]);
			M[i] = std::max(M[i], view[i]);
		}

		BarAndSpaceI res;
		for (int i = 0; i < 2; ++i) {
			// check that
			//  a) wide <= 4 * narrow
			//  b) bars and spaces are not more than a factor of 2 (or 3 for the max) apart from each other
			if (M[i] > 4 * (m[i] + 1) || M[i] > 3 * M[i + 1] || m[i] > 2 * (m[i + 1] + 1))
				return {};
			// the threshold is the average of min and max but at least 1.5 * min
			res[i] = std::max((m[i] + M[i]) / 2, m[i] * 3 / 2);
		}

		return res;
	}

**Comment by tigerdhl** [comment]
> Could you please post the complete message from the compiler regarding this specific line? (typically a couple lines of output from the compiler explaining the issue for one line of source code.)

the problem descrip this “initializer list”can not transform to“ZXing::BarAndSpaceZXing::PatternView::value_type”
and I found the problem come from function of the file "ODRowReader.h" follows:

`static BarAndSpaceI NarrowWideThreshold(const PatternView& view)
	{
		BarAndSpaceI m = { 

> std::numeric_limits<BarAndSpaceI::value_type>::max(),std::numeric_limits<BarAndSpaceI::value_type>::max()};
> 		BarAndSpaceI M = {0, 0};

		for (int i = 0; i < view.size(); ++i) {
			m[i] = std::min(m[i], view[i]);
			M[i] = std::max(M[i], view[i]);
		}

		BarAndSpaceI res;
		for (int i = 0; i < 2; ++i) {
			// check that
			//  a) wide <= 4 * narrow
			//  b) bars and spaces are not more than a factor of 2 (or 3 for the max) apart from each other
			if (M[i] > 4 * (m[i] + 1) || M[i] > 3 * M[i + 1] || m[i] > 2 * (m[i + 1] + 1))
				return {};
			// the threshold is the average of min and max but at least 1.5 * min
			res[i] = std::max((m[i] + M[i]) / 2, m[i] * 3 / 2);
		}

		return res;
	}`

**Comment by tigerdhl** [comment]
> Could you please post the complete message from the compiler regarding this specific line? (typically a couple lines of output from the compiler explaining the issue for one line of source code.)

the problem descrip this “initializer list”can not transform to“ZXing::BarAndSpaceZXing::PatternView::value_type”
and I found the problem come from function of the file "ODRowReader.h" follows:

`static BarAndSpaceI NarrowWideThreshold(const PatternView& view)
	{
		BarAndSpaceI m = { std::numeric_limits<BarAndSpaceI::value_type>::max(),std::numeric_limits<BarAndSpaceI::value_type>::max()};
		BarAndSpaceI M = {0, 0};
		for (int i = 0; i < view.size(); ++i) {
			m[i] = std::min(m[i], view[i]);
			M[i] = std::max(M[i], view[i]);
		}

		BarAndSpaceI res;
		for (int i = 0; i < 2; ++i) {
			// check that
			//  a) wide <= 4 * narrow
			//  b) bars and spaces are not more than a factor of 2 (or 3 for the max) apart from each other
			if (M[i] > 4 * (m[i] + 1) || M[i] > 3 * M[i + 1] || m[i] > 2 * (m[i + 1] + 1))
				return {};
			// the threshold is the average of min and max but at least 1.5 * min
			res[i] = std::max((m[i] + M[i]) / 2, m[i] * 3 / 2);
		}

		return res;
	}`

**Comment by axxel** [comment]
I see. Your compiler is too old to compile c++-14 code. You need at least VS 2017: https://godbolt.org/z/jod54W.

Even better: get yourself the latest version because we'll require c++17 soonish.

**Comment by tigerdhl** [comment]
> I see. Your compiler is too old to compile c++-14 code. You need at least VS 2017: https://godbolt.org/z/jod54W.
> 
> Even better: get yourself the latest version because we'll require c++17 soonish.

got it,thank you
