### ISSUE TITLE
PDF417 South African Driver License reading is not working

### ISSUE THREAD

**Issue by Sarmini-M** [nu-book/zxing-cpp#152]
Could you have a look at the scanning of South African driver's licenses?

I have tried several ideas (preprocessing, few tweaks in pdf417 detector and decoder), but nothing works so far.
Always I am getting a large number of erasures in the final result. My goal is just to have a valid decoded bytes in the output.

Any advice would be appreciated.

**Comment by axxel** [comment]
Could you pleas provide a sample image and provide both the expected and the returned/wrong result?

**Comment by Sarmini-M** [comment]
Thanks for quick response.

I can share a publicly available driving licence which also doesn't work when using Xzing pdf417 reader.
The expected output should be a valid ZXing::Result  (DecodeStatus::NoError) that has data in "decodedBytes" ByteArray
The returned result is DecodeStatus::ChecksumError.

I have tried several South African driving licences and didn't get a valid output.

![1](https://user-images.githubusercontent.com/6943671/90515723-b5702f80-e16b-11ea-9760-a89bc1a21f93.jpg)

**Comment by axxel** [comment]
I'm not familiar with the PDF417 code base but have a rough idea how it is supposed to work. I had a look at where the code bails and found that the main issue here seems to be that the decoder seems [fundamentally incapable](https://github.com/nu-book/zxing-cpp/blob/915477cc59a193b556e0c7e68183acf8a54e6236/core/src/pdf417/PDFDetectionResultColumn.cpp#L158) of detecting codes that are upside-down, which seems to be the general case for ZA drivers licenses?

Flipping the image upside down was not sufficient to make it work, though. I also had to rotate it to be perfectly level. See also my remarks in #145.

The straightened and vertically flipped image did give some results then.
![Working-ZA-drivers-license](https://user-images.githubusercontent.com/1038346/90550030-a7340a80-e18f-11ea-8373-5396a444e52e.jpg)

If you have a higher resolution scan, you might get away with only flipping it vertically and without perfectly straightening it. Please let me know what you find.

**Comment by Sarmini-M** [comment]
Thanks @axxel 
Indeed flipping the detected barcode (detect the barcode then cropping it) and giving attention to its rotation do help in decoding it.

So flipping is a MUST for ZA pdf417 barcodes, rotation is very important but it is not necessarily to be perfectly level ( I mean 0 degree ) especially for good resolution and clean images (images that are not noisy, blurry, or have pixelation)

**Comment by tailsu** [comment]
@axxel The following fix made it work for me without having to flip the image:

```
+       int increment = 1;
        for (int codewordsRow = firstRow; codewordsRow < lastRow; codewordsRow++) {
                if (codewords[codewordsRow] == nullptr) {
                        continue;
                }
                Codeword codeword = codewords[codewordsRow];
+               if (barcodeRow == -1 && codeword.rowNumber() == barcodeMetadata.rowCount() - 1) {
+                   increment = -1;
+                   barcodeRow = barcodeMetadata.rowCount();
+               }

                //      float expectedRowNumber = (codewordsRow - firstRow) / averageRowHeight;
                //      if (Math.abs(codeword.getRowNumber() - expectedRowNumber) > 2) {
@@ -155,12 +160,10 @@ DetectionResultColumn::adjustCompleteIndicatorColumnRowNumbers(const BarcodeMeta

                int rowDifference = codeword.rowNumber() - barcodeRow;

-               // TODO improve handling with case where first row indicator doesn't start with 0
-
                if (rowDifference == 0) {
                        currentRowHeight++;
                }
-               else if (rowDifference == 1) {
+               else if (rowDifference == increment) {
```

**Comment by axxel** [comment]
@tailsu Thanks! Would you care sending a PR (adding a paper trail of your contribution)? :)
