### ISSUE TITLE
Android anyone?

### ISSUE THREAD

**Issue by axxel** [nu-book/zxing-cpp#153]
I looked into adding an android build to the CI system and noticed two things:

1. I seem to have broken the format specification feature of the android wrapper a while ago but no-one complained. Is there anyone actively using the android wrapper?

2. Nowadays the way to build external C++ libraries for android seems to be cmake with toolchain files instead of via ndk-build `*.mk` files. I see a benefit in removing the duplicated information in and currently outdated `*.mk` files. Anyone relying on those?

@vkrause?

**Comment by vkrause** [comment]
We are using the normal C++ API and the CMake build system on Android as well, ie. exactly the same as we are using this on all other platforms. So no objection from our side regarding removing any of those.

**Comment by axxel** [comment]
@vkrause thanks for the prompt reply.

Question: what do you mean you use the "normal C++ API"? You have your own JNI wrapper? Or is there another trick to get access to zxing from a JVM-based app?

**Comment by vkrause** [comment]
The part of our application using zxing is written in C++, so we don't even need to access this from Java at all.

**Comment by huycn** [comment]
It seems that WinRT wrapper is also broken with the change in format. I will fix both of them.
Build with CMake is a good idea. I remember I've tried quickly to do that but I was rather complicated than I thought with the structure of CMakeLists.txt that we had. As now it has changed, I will try again.

**Comment by axxel** [comment]
I see you updated the ndk-build files instead of removing them. Did the "switch to cmake" attempt fail?

**Comment by huycn** [comment]
Yes, my first attempt failed but I will try again. In the mean time, I pushed the fix for BarcodeFormat first.

**Comment by axxel** [comment]
@huycn I've been working on the android plugin lately and I have a `cmake` + AndroidStudio/gradle based setup that builds the jni library and a new Kotlin wrapper and also includes a demo app that can be used to actually run the code on a phone and play with it a little (like setting the tryRotate flag or cropping the viewport, etc.) and also includes a button to switch over to the upstream Java code for quick runtime and detection quality comparisons. I intend to use that to replace the current *.mk build setup but wanted to know if relying on AndroidStudio/gradle would be a hassle for you? It would still be possible to call `cmake` manually but I would need to find out how and document it.

**Comment by huycn** [comment]
@axxel I will be no problems for us, and I don't think there are people out there develop for Android without Android SDK :)
So your changes will be welcome.

**Comment by axxel** [comment]
@huycn Once you can confirm that the new wrapper implementation is working for you, I'll remove the old one and update the `README.md` accordingly.
