### ISSUE TITLE
How to communicate a mirrored/flipped 2D code?

### ISSUE THREAD

**Issue by axxel** [nu-book/zxing-cpp#155]
The `Result` class provides a `position` and an `orientation` member. The position is a set of 4 points with names like `topLeft`, etc. Currently at least the QRDecoder can find out if a symbol is mirrored/flipped. If so, it swaps the `bottomLeft` and `topRight` points. This results in a non-intuitive result for the orientation (which I first thought of as a bug when looking at #142).

I believe the current behavior is non-ideal and we should leave the 4 corners in order and either discard the mirrored/flipped bit or provide it explicitly as a boolean flag in the `Result` struct.

Anyone interested in this type of information, at all? (@huycn @vkrause)

**Comment by huycn** [comment]
We don't really use these fields in our projects.

**Comment by vkrause** [comment]
same here, we only use the decoded content, how exactly it was encoded doesn't matter for our use-cases

**Comment by axxel** [comment]
Since no one is using this information and it would currently only be available from the QRCode reader, I will not spent time on this until someone actually has a use for it.
