### ISSUE TITLE
Removal of UPC_EAN_EXTENSION enum

### ISSUE THREAD

**Issue by axxel** [nu-book/zxing-cpp#159]
Is anyone using the BarcodeFormat::UPC_EAN_EXTENSION enum value?

Background info: This enum value is in the list of supported barcode formats, but it is not a format and does not behave like the other values. What it does is basically provide an alternative to the option of setting the `DecodeHints::allowedEanExtensions` array to `{2,5}`, meaning you want to only accept `EAN-13 / UPC-A / UPC-E` codes with either an `EAN-2` or an `EAN-5` add-on symbol.

That whole thing is inconsistent in a number of ways:
 1. if you specify it as the sole requested format, you never get any result.
 1. you'll never get that enum value back as the found format.
 1. it is the only `DecodeHints` option you have two ways to specify.

While I'm complaining anyway: the name and the type of `allowedEanExtensions` is misleading and confusing, too. First of all, these things are called "add-on symbols" in the specification, not "extensions". These add-ons are always allowed, i.e. if they get detected, you'll get them reported in the metadata. What the option actually means is "I require at least one of these add-ons". Also, modeling that as a list of arbitrary integers of which only the values 2 and 5 have any effect is suboptimal from a usability point of view.

The problem to be solved here is the following: You want to detect barcodes with theses add-ons and want to make sure they are properly searched for. You don't want the default behaviour where the decoder might return a result without the add-on because it found a scanline with a proper main part but a scrambled add-on part. You want it to discard this scanline and keep on looking until it finds one with both parts intact.

My suggestion to comminicate this to the decoder in a more user friendly and self-explanatory way:

Replace all the above with a single boolean flag in `DecodeHints` named `requireEanAddOnSymbol`.

As usual, feedback welcome and silence is an implicit approval. :)

**Comment by enzo-simone** [comment]
Hello, we are currently handling this particular scenario in the business logic of our project, so there's no use for `BarcodeFormat::UPC_EAN_EXTENSION` enumeration value. Thanks.

**Comment by axxel** [comment]
Thanks for the feedback but there must be a misunderstanding somewhere: if you neither use the enum nor the `allowedEanExtensions` array, then you can not (practically) achieve the intended effect from outside the library. What you would have to do is feed your image into the library line by line, I assume you are not doing that?

**Comment by enzo-simone** [comment]
In our case ZXing is wrapped into a legacy barcode decoding library which can be configured both for sought symbology(ies) and barcode lengths, so we internally enable ZXing symbology(ies) according to symbology(ies) configured in our barcode library (handling possible ambiguities) and, after decoding, we filter decoded barcodes by lengths.
Hope this makes sense.

**Comment by axxel** [comment]
I think I see what you mean. That approach would certainly work if you have clean input data because you'll always get the add-on data if it is present. In case your input is barely detectable you could potentially get results including the add-on if you explicitly requested it and miss it otherwise. Anyway, you don't rely on the `UPC_EAN_EXTENSION` enum and that is what I wanted to know.
