### ISSUE TITLE
Anyone using any of the Reader classes directly?

### ISSUE THREAD

**Issue by axxel** [nu-book/zxing-cpp#165]
Does anybody instantiate individual reader classes directly instead of going through either the `MultiFormatReader` class or the new `ReadBarcode` function? I'm especially interested in the UPC/EAN and the two RSS variants. In the wake of #89 I'm about to flip the switch to use the new/faster implementation and remove the old. That would naturally lead to a removal of those classes as they are subsumed by their 'multi'-versions. I could keep wrappers for single codes that simply call back into the multi-versions but that would require effort and produce boilerplate code that I doubt anyone is using right now anyway.

In general I'd like to reduce the surface of the public facing API (or rather the part that is supposed to be stable), exactly to allow for those kind of optimizations without unnecessary worries about downstream dependencies on 'internals'.

As usual, feedback welcome, especially from @huycn, @vkrause.

**Comment by huycn** [comment]
In our projects, we use only `MultiFormatReader` with a default-constructed `DecodeHints`. Thus, your changes will be welcome :)

**Comment by vkrause** [comment]
`MultiFormatReader` here as well, so no objection either :)

**Comment by axxel** [comment]
Thanks for the feedback. They will then go away. I just added a new `DataBar` reader, only one more to go (DataBarExpanded).
