### ISSUE TITLE
Detect Data Matrix DPM ?

### ISSUE THREAD

**Issue by postflow** [nu-book/zxing-cpp#167]
Is it capable this library detect Data Matrix DPM like on photo ?
![Безымянный](https://user-images.githubusercontent.com/5417589/97666758-5f830680-1a8f-11eb-8ec5-770cb3ca3855.png)

**Comment by axxel** [comment]
Unfortunately not, at least not without preprocessing your image. Please see #53 for more details.

**Comment by neycyanshi** [comment]
@axxel , also this is an inverted code, which has white module instead of black module. Current DMDetector do not support these inverted codes, but there are many inverted DataMatrix codes in use. Is there any related issue?
