### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by mfulton26** [nu-book/zxing-cpp#176]
It would be awesome to have an officially published npm (or GitHub) package with prebuilt .wasm file, etc.

**Comment by axxel** [comment]
Did you see the comment about prebuild wasm files that can be found on the Actions page?

If you see the need for and have the expertise, please don't hesitate to provide a PR for the addition of automatic GitHub package creation via our CI scripts. I don't know what an npm user would need (and don't have the time to find that out first ;)).

**Comment by axxel** [comment]
Closed for lack of feedback.
