### ISSUE TITLE
Encountered a BUG when detecting PDF417 code

### ISSUE THREAD

**Issue by gong-xiaomei** [nu-book/zxing-cpp#180]
Encountered BUG when detecting PDF417 code

When I try to read the PDF417 code with the latest code using _binarizer(Binarizer::LocalAverage), if the PDF417 code image is slightly blurred, this BUG will be reported.
Note that it will not be reported when the picture is clear.
The error message is as follows:
Debug Assertion failed!
expression: cannot dereference end map/set iterator
For information on how your program can cause an assertion failure, see the visual c++ documentation on asserts.

May I ask what is the problem, can you help me ?
![20-12-10-16-03-14](https://user-images.githubusercontent.com/56329003/101978703-d36d1d00-3c91-11eb-953b-fb9d9ad4c255.jpg)
![bug](https://user-images.githubusercontent.com/56329003/101978707-dd8f1b80-3c91-11eb-9c4b-d6e3e2c0e18f.PNG)

**Comment by axxel** [comment]
I have not been able to reproduce your issue. Can you try it with the `ZXingReader` example application and let me know the commandline parameters that you used?

**Comment by gong-xiaomei** [comment]
I am using the unreleased version under master
After I used the latest version 1.1.1, the above problem did not occur。
Thank you for your reply。

**Comment by axxel** [comment]
Thanks but that information is still not enough for me track down the problem. I need to be able to reproduce the issue on my machine. Can you reproduce the problem with the `ZXingReader` example application?

**Comment by gong-xiaomei** [comment]
I tried to download the code under the master, 
https://github.com/nu-book/zxing-cpp
![image](https://user-images.githubusercontent.com/56329003/103122350-cfda8c80-46ba-11eb-8255-cf1535d4d69b.png)

![20-12-10-16-03-14](https://user-images.githubusercontent.com/56329003/103122369-ec76c480-46ba-11eb-93ce-b7dfb49493c7.jpg)


and after generating the .sln file according to the following steps, a ZXing.lib file was generated,
### Windows GDIPlus wrapper
1. Open CMake GUI, specify [`wrappers/gdiplus`](wrappers/gdiplus) as source folder in the first input, specify the build output in the second input, and click on Generate.
2. At prompt, select "Visual Studio 15 2017" (or "Visual Studio 15 2017 Win64" if you want to build for x64 platform); leave the second input (Optional toolset...) empty; leave "Use default native compilers "checked; and click on Finish to generate the VS project. At the end, you will get a solution (.sln) in your binary output directory that you can open in VS. The project ZXingGdiPlus in the solution will generate a static library.

Then I create a C++ project, refer to the code in the example [`ZXingReader.cpp`](example/ZXingReader.cpp). Reference the generated ZXing.lib library file, and 100% error is reported after execution. I wonder if there is a problem with my PDF417 image generation?
