### ISSUE TITLE
All improvements for PDF417 works in WebAssembly?

### ISSUE THREAD

**Issue by sybrin-innovations** [nu-book/zxing-cpp#194]
Hi,

I just want to check if the change made for issue https://github.com/nu-book/zxing-cpp/issues/152 
where also build for the WebAssembly file.

I have taken the new zxing_reader.wasm from the action section. I can scan all other all barcode fine, except when it comes to the PDF417 that can be found in the issue above.

I saw there was a fix, just wanted to know if it was built for all uses?

**Comment by axxel** [comment]
The drivers license sample had two issues: a) the symbol is laid out upside-down and b) the for the current implementation to detect it, it needs to be less tilted. The issue with a) has been fixed and should also be available in the WASM build. The second issue still remains.

**Comment by axxel** [comment]
If you don't have further comments, please close this issue.
