### ISSUE TITLE
Whether the JNI interface supports BinaryBitmap.

### ISSUE THREAD

**Issue by liupd1996** [nu-book/zxing-cpp#203]
Hello:
       It is more convenient for the camera to scan the code use the method of 
       [BarcodeReader](https://github.com/nu-book/zxing-cpp/blob/master/wrappers/android/java/com/zxing/BarcodeReader.java).read(BinaryBitmap bitmap)  instead of
       BarcodeReader.read(Bitmap bitmap)

     Are there additional interfaces?
     Best Regard!

**Comment by liupd1996** [comment]
Hmm...  yeah,there is not. What I mean is that when I use the camera to scan, what the camera returns to me is YUV data byte. It seems that I need to convert it into bitmap to use Android API.
Maybe adding a Android APIs of BarcodeReader(byte[] data,....) or BarcodeReader(BinaryBitmap bitmap,....) looks good?BinaryBitmap is java class of original Zxing library.

**Comment by liupd1996** [comment]
Hmm...  yeah,there is not. What I mean is that when I use the camera to scan, what the camera returns to me is YUV data byte. It seems that I need to convert it into bitmap to use Android API.
Maybe adding a Android APIs of BarcodeReader(byte[] data,....) or BarcodeReader(BinaryBitmap bitmap,....) looks good?BinaryBitmap is java class of original Zxing library.

**Comment by axxel** [comment]
I have been working on a new `BarcodeReader` for Android implementation a while back (mainly to be able to deprecate some internal c++ interfaces). I'll try to bring it to a usable state and commit the changes 'soonish'. The interface will allow to call the `read` function directly on an `ImageProxy` object from the Camera2/CameraX API containing `YUV_420_888` data.

I'm curious: what is your reason to use this JNI wrapped c++ project instead of the upstream Java project?

**Comment by liupd1996** [comment]
I think .so library is hard to decompile, Java code is easy, and Android ProGuard is not secure when you want to add extra functionality or custom code and need to keep it secret.

**Comment by axxel** [comment]
So your motivation is to be able keep proprietory changes secret? If you are changing the code anyway, you should be able to modify the API to your liking without help from the open source community... ;).

**Comment by axxel** [comment]
See my recent Android related commit.

**Comment by liupd1996** [comment]
Thank you for your commit.
Best regard!
