### ISSUE TITLE
Improve user experience when reading EAN/UPC codes with Add-on symbols

### ISSUE THREAD

**Issue by axxel** [nu-book/zxing-cpp#207]
I'd like to get rid of the `ResultMetadata` API (in the long run). This type erasure + map approach feels very cumbersome to use and is mostly an artifact of this code having been ported from Java. I already deprecated the `ORIENTATION` tag a while ago. Now during reviewing #205 I came to the conclusion that the EAN Add-on symbol handling could also be made more straight forward:

* replace the `bool DecodeHints::requireEanAddOnSymbol` with an enum `EanAddOnSymbol { Ignore, Read, Require }`
* if an add-on symbol was read, append its text value after a ' ' (or '+'? see discussion in #205) to the standard text output
* move the `ISSUE_NUMBER`, `SUGGESTED_PRICE`, `POSSIBLE_COUNTY` fields into simple text processing functions

So, if you are interested in those add-ons, you set your hints to `Read` or `Require` and split your result text at the space if you need that separated. The default value should probably be `Ignore`.

Any objections / opinions? (@huycn, anyone?)

**Comment by huycn** [comment]
I agree that `ResultMetadata` is cumbersome and not very C++ oriented. And no, I don't have any objection, it sounds good to me.
