### ISSUE TITLE
Who uses PDF417_EXTRA_METADATA from ResultMetadata struct?

### ISSUE THREAD

**Issue by axxel** [nu-book/zxing-cpp#210]
In continuation of my effort to deprecate the current usage model of the `ResultMetadata` class, I'd like to get rid of the `PDF417_EXTRA_METADATA` use case. The information stored under that key can be divided in 2 parts: 

 1. `segmentIndex` to sort codes that spread across multiple symbols. This is basically a duplication of what `STRUCTURED_APPEND` information is for the QRCode and is currently used in the blackbox tests.
 1. `OPTIONAL_FIELD` entries such as `fileName` or `sender` that are purely PDF417 specific.

Number 1) can be mapped to the structured append keys (and later ported into plain members of the `Result` class) and 2) can be ignored if no one uses them anyway or moved over to a single format specific 'custom data' struct, much like what you get behind `PDF417_EXTRA_METADATA` right now, but without the `ResultMetadata` class in-between.

I'd like to know if anyone uses `PDF417_EXTRA_METADATA` at all. @huycn, @gong-xiaomei, @Sarmini-M, @vkrause, @tailsu ?

**Comment by vkrause** [comment]
We aren't using any of this to my knowledge, I didn't even know this existed :)

**Comment by axxel** [comment]
I just committed a change dealing with the structured append part of the meta data. And due to lack of interest, I will simply drop the other half from the public interface until someone actually has a use for it.
