### ISSUE TITLE
Aztec barcode with default size and quiet zone cannot be decoded

### ISSUE THREAD

**Issue by antoinehumbert** [nu-book/zxing-cpp#217]
When creating an Aztec barcode with default (minimum) size and default quiet zone (no quietzone !) leads to an unreadable barcode.

Steps to reproduce (using python API):

```python
img = zxing.write_barcode(zxing.BarcodeFormat.Aztec, "I have the best words.")
res = zxing.read_barcode(img)
assert res.valid  # False
```

The generated image is 19x19 pixels and does not contain any quiet zone.
If image is generated with `img = zxing.write_barcode(zxing.BarcodeFormat.Aztec, "I have the best words.", quiet_zone=10`, the image is then correctly decoded by `read_barcode`.
If image is generated with `img = zxing.write_barcode(zxing.BarcodeFormat.Aztec, "I have the best words.", width=38, height=38)`, the image is then correctly decoded by `read_barcode`.

Aztec barcodes do not require any quiet zone and looking at generated barcodes images, the default size (19x19) and 38x38 size images have exactly the same modules (unlike the scale factor). Finally, getting the 19x19 image and rescaling to 38x38 (using NEAREST interpolation to avoid blur) gives exactly the same pixels as the generated 38x38 image, and is then correctly decoded.

The problem looks related to decoder and tiny images.

**Comment by antoinehumbert** [comment]
Image size seems not to be the only problem. Here is another use case:

```python
img = zxing.write_barcode(BF.Aztec, "Hello guy")  # img has size 15x15
assert zxing.read_barcode(img).valid  # Ok
img = zxing.write_barcode(BF.Aztec, "Hello guys")  # img has size 15x15
assert zxing.read_barcode(img)  # Ko
img = zxing.write_barcode(BF.Aztec, "Hello guys", width=30, height=30)  # img has size 30x30
assert zxing.read_barcode(img).valid  # Ok
```

**Comment by antoinehumbert** [comment]
After investigating, it seems the problem is in detection of bull-eye center. On the first example (19x19 image), bull-eye center is detected at position (8, 10) whereas center is at (9, 9).
Forcing center coordinates to (9, 9) in the code leads to correct detection of the barcode.

I will investigate more what could happen in the GetMatrixCenter function.

**Comment by antoinehumbert** [comment]
Here is my analyzis of the problem in AztecDetector.cpp / GetMatrixCenter :

This is not clear if the detection of white rectangle if for the Bull's eye white rectangle or for a quiet zone around the whole aztec code. In my opinion, as Aztec does not need quiet zone, we should search for the bull's eye white rectangle and not for a white rectangle around the barcode.

The first white rectangle detection (line 422) cannot find any white rectangle for a bull's eye of size 9x9 (the smallest possible size for bull-eye which is the case for my small aztec code in test), as it starts with a 10x10 initial rectangle.
So, it then search for black points starting with a rectangle of size 15x15 and expanding rectangle : this is where I think there are two mistakes, as the result does not clearly give a rectangle :
- starting with a rectangle of -7 / +7 around the center seems to suit a bull's eye of size 13x13 (i.e. core of 15x15) that is too big for a bull's eye of 9x9
- the search is done by expanding the rectangle whereas the black rectangle around the bull's eye is "inside" the search rectangle, so we should shrink rectangle and not expand

In the same manner, the following "refinement" (search again around the first found center) seems also based on a bull's eye of 13x13 (i.e. core of 15x15).

Finally, by doing the following changes, I can get detection working for small aztec codes with 9x9 bull's eye:

- inside both "if" clauses : change 7 to 5 for starting rectangle. Change the dx/dy 1 <-> -1 to shrink the search rectangle instead of expanding
- in the second call to DetectWhiteRect, set initSize to 11 instead of 15

I expect this approach to work for 13x13 bull's eye as well as for 9x9, detecting the outer bull's eye square for a 9x9 and the inner square for a 13x13 bull's eye, that would give both the same center.

What do you think about this analysis ? Should I propose a PR ?

**Comment by axxel** [comment]
Thanks for your detailed analysis. Shrinking instead of enlarging the rectangle will not generally work. The problem was the wrong initial search rectangle (of arbitrary size 10x10). That was clearly not meant to work with a tiny (module size 1) image.

Note: that whole `DetectWhiteRect` based approach is not working at all if the symbols are not (almost) perfectly straight (like the ones in samples/aztec-2). There needs to be something completely different here to be usable in 'the real world'.
