### ISSUE TITLE
Can anyone share the dll of CPP program

### ISSUE THREAD

**Issue by niravpatel** [nu-book/zxing-cpp#230]
Can anyone share the dll of CPP program, as I am .NET developer and want to utilize in my project

**Comment by axxel** [comment]
We don't supply binary builds. I suggest you build it yourself. With a Visual Studio already installed you only need to install cmake and you are ready to go. See the README.md file.

**Comment by niravpatel** [comment]
Thanks for valuable reply, I tried but it was showing error for few header
files such as emscripten/bind.h file. We couldn't found as such file in
your solution.

**Comment by axxel** [comment]
You need to open and build the top level `CMakeLists.txt`. If there is something about emscripten, then you opened the wrong cmake project file.
