### ISSUE TITLE
How to compile the v1.2.0 version with VisualStudio?

### ISSUE THREAD

**Issue by lizq-git** [nu-book/zxing-cpp#233]
Hi, guys.

Did any of your guys successfully compile the v1.2.0 using cmake? 

This is what I have tried, method 1.

1. Clone the repo: https://github.com/nu-book/zxing-cpp
2. Using camke 3.20.3
3. [Browse Source] direct to the: ../zxing-cpp
4. [Browse Build] direct to the: ../zxing-cpp/build

Method 2: repeat [1-4] using the v1.2.0 tag.

Both the methods failed to create the .sln.

Am I doing it wrongly?

**Comment by huycn** [comment]
Please tell us:
1) Which version of VS installed on your computer?
2) What are your choices in generator dialog (e.g. Visual Studio 16 2019, Win32) after you click on "Generate"?
3) What are errors reported by CMake when you click on "Finish"?

**Comment by lizq-git** [comment]
> Please tell us:
> 
> 1. Which version of VS installed on your computer?
> 2. What are your choices in generator dialog (e.g. Visual Studio 16 2019, Win32) after you click on "Generate"?
> 3. What are errors reported by CMake when you click on "Finish"?

Thank you for the quick response, I was trying to compile it as well.

To answer your questions:
1. VS2019 as the tutorial steps are suggesting to use: VS2019.
2. I have 28 options, QT5_dir is also included.
3. I am good to generate even with the missing QT5 directory.
 -->     Qt5Config.cmake
 --> qt5-config.cmake


I was then able to use the built - Zxing.sln to build a running .exe. But I failed to have the zxing.dll ready. (I have change the "config type" to .dll instead of exe.

Also, I can generate the Zxing.lib under - **\zxing-cpp\build_main\core\Release\Zxing.lib

**Comment by lizq-git** [comment]
Hi @huycn 

Thank you, I am able to use CMAKE to build a x64 lib, and then make a DLL out of it.

But I failed to CMAKE de x86 lib, is this because this version doesn't support x86?

**Comment by huycn** [comment]
In CMake UI, put a **new** path for binary output. Click on *Configure*, wait for it finish, then look for "BUILD_SHARED_LIBS" in the panel above and check to enable it. After that click on *Generate*. I did that with Win32 as platform and the project generates a DLL as expected.

Note that set new path for binary output is important as it will prevent CMake from using cached files. You can also do "File/Delete Cache" which is the same.

**Comment by lizq-git** [comment]
@huycn thanks, I am able to generate x86 and x64 dll by using VS2019 generator. 

I have then used the same method but a different generator, but it then failed, does that means the current version doesn't support the other VS version as a generator option?

**Comment by huycn** [comment]
At least VS2017 should also work. Which other generator did you use? Did you clear cache or use different destination folder when changing generator?

**Comment by lizq-git** [comment]
@huycn I have tried with VS2017, but it failed, yes I did that as well.

I am hoping could use VS2013, but the workaround for that will be using CMD mode - run the exe. (this is what I have done)

**Comment by axxel** [comment]
Note: as per our README the minimum required version is "VS 2019 16.8" (because of the required C++17 support, iirc).

**Comment by lizq-git** [comment]
@axxel @huycn thank you both for answering and open-source such a great repo.

I am using a workaround for this issue I faced, which is running via the exe, than you.
