### ISSUE TITLE
Compile error for v1.2.0 version with VisualStudio2019

### ISSUE THREAD

**Issue by weixing19** [nu-book/zxing-cpp#237]
windows10 x64，VisualStudio2019 V16.0，Compile with win32 , ZXing succesed，can created .lib，ZXingWinRT failed，error message：

fatal error C1107: could not find assembly 'platform.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable ZXingWinRT	
E:\workshop\zxing-cpp\wrappers\winrt\BarcodeReader.cpp	1

**Comment by axxel** [comment]
@huycn Maybe you have an idea?

**Comment by weixing19** [comment]
I don't know how to deal with the problem，how should i do？thanks。

**Comment by huycn** [comment]
Please provide us details  how you build the project. Do you follow instructions in Readme?
I've just build it again without issue. All I did were to modify wrappers/winrt/BuildWinCom.bat to change the -G flag from "Visual Studio 15 2017" to "Visual Studio 16 2019" (as I only have VS2019 installed) and run that batch script.

**Comment by weixing19** [comment]
myself add platform.winmd to project ,it's OK,thanks.
