### ISSUE TITLE
Android Demo QRCode not working?

### ISSUE THREAD

**Issue by kim-ninh** [nu-book/zxing-cpp#238]
Thank you a lot for having an android demo for this awesome library. 

Unfortunately, when I run the app with a live preview camera, no QR code is detected. I've tried all tuning options: rotate, java, crop but no hope 😢. 

Any suggestion?

https://user-images.githubusercontent.com/28674990/126895909-0411e2c6-e9d7-4c98-9843-17c7388d6796.mp4

**Comment by axxel** [comment]
It seems you try to scan that from a Monitor. That can be difficult due to aliasing/moire artifacts coming from taking high res images from a pixelated monitor. Please try two things: a) move the phone away from the monitor b) try a QRCode that is printed on paper. I can successfully scan this QRCode with my phone from the video you posted.

**Comment by kim-ninh** [comment]
I've tried as you said, but no luck. By the way, do you think it's related to the CameraX? As far as I know, that library is just released recently, and may still have some bugs. In the original repo of zxing using java, I successfully scan the QRCode not only from paper but also on the monitor. 

I'm using Xiaomi Redmi 5 Plus, the preview size is 1280x720 but the ProxyImage size is 864x480.

**Comment by kim-ninh** [comment]
I've changed the target aspect ratio for both preview use case and image analysis use case to 4:3 and it's working now (The preview size is 1440x1080 and preview frame size is 640x480).

**Comment by axxel** [comment]
I've only tested this demo on my Google Pixel 3, where I get an ImageAnalysis/ProxyImage resolution of 1280x720. I don't see why the aspect ratio should make a difference (maybe there is a bug in the memory layout somewhere?). Those 480 pixels is not much but definitively enough for that particular QRCode (and completely invalidates my original idea about aliasing, as the downsampling to 480 would take care of that).

It would be interesting if you could find out why the aspect ratio change works for you.

**Comment by kim-ninh** [comment]
Okay, this is really weird. When I use the 4:3 ratio, the preview frame data is *correct*. But when switch to 16:9 ratio, the preview frame data is broken, maybe a bug from CameraX :)

Here is the preview frame I've taken from my device and encode it into PNG

![preview_data_frame_640x480](https://user-images.githubusercontent.com/28674990/128621983-ad0e69d9-3d60-433c-9f85-0e48d70c19e9.png)
This one has res 640x480 (4:3 ratio)

![preview_data_frame_864x480](https://user-images.githubusercontent.com/28674990/128621987-df8851e2-fdf9-4eee-a734-42f39eccf250.png)
And this one has 864x480 (16:9 ratio)

**Comment by axxel** [comment]
I expected something like this. Looking at the second image, it seems that the rowstride is 32 pixels too small. The question is: where exactly did you extract that data from within the pipeline. Looking at your new `readYuvNative` function, there is a bug there that would perfectly explain this outcome:
```c++
auto image = ImageView(yBytes, width, height, ImageFormat::Lum, width)
```

The last parameter has to be the correct row-stride which is not guaranteed to be equal to the `width` of the image (we would not need the parameter then).

**Comment by kim-ninh** [comment]
I just want to make clear this first. The screenshot I've taken is from the master branch of this repo, not the fork on my PR :). So definitely it is the bug of Android framework :)
By the way, everything works as normal when I try to explicitly set the target resolution to 720x1280 to both preview's use case and imageAnalysis's use case. Here is where I set the target resolution:

https://github.com/nu-book/zxing-cpp/blob/63523d2306563c0e4bab69ea845995ac8e5728d6/wrappers/android/app/src/main/java/com/example/zxingcppdemo/MainActivity.kt#L85

https://github.com/nu-book/zxing-cpp/blob/63523d2306563c0e4bab69ea845995ac8e5728d6/wrappers/android/app/src/main/java/com/example/zxingcppdemo/MainActivity.kt#L91

**Comment by kim-ninh** [comment]
And the preview frame I've taken from the very beginning of the callback, before feed it to BarcodeReader.

**Comment by axxel** [comment]
Interesting. 2 things I'd like to add:
 1) if you could fire up a debugger and see what value gets passed as `rowStride` in [this line](https://github.com/nu-book/zxing-cpp/blob/63523d2306563c0e4bab69ea845995ac8e5728d6/wrappers/android/zxingcpp/src/main/cpp/BarcodeReader.cpp#L105) and also maybe see what happens if you add a `+32` as a quick way to confirm my theory (and your's about who's fault it is ;)).
 2) I just updated a bunch of dependencies, cameraX being one of them. Maybe the 1.0.1 release version has a fix for your issue.

**Comment by kim-ninh** [comment]
1. Yes I understand the row stride is the number of bytes per row. When feeding the data coming from the camera, we just need the y plane, each pixel has 1 byte so the row stride is the same as the image width. In another case, for the RGBA image, the row stride should be 4 * width. 
2. Well, I just already use the latest stable version from Google but no luck.

P/s: I've been working on another project using this zxing-cpp. That project still using the legacy camera API and it still works fine so I've believed the bug coming from Google =)

**Comment by axxel** [comment]
1. That is not necessarily true. It could also be that you have a y-plane that contains an e.g. 15 pixel wide image but each row starts at an address that is divisible by 16. That means there would be one 'dummy' byte at the end of each row. In your case there seem to be 32 dummy bytes which are not accounted for. Therefor my suggestion to look at the specific numbers in your case. It could also be that there is a bug in the zxing code that just has not shown, yet since all other experiments had a rowStride of exactly width bytes (by accident).
 2. too bad :-/.

**Comment by kim-ninh** [comment]
I think I have figured out the root cause, and you're right! There has some padding bytes at the end of each row. Here is the log contain the information about the pixel stride, row stride of the y-plane get from ImageProxy.

![image](https://user-images.githubusercontent.com/28674990/128639221-09fc84a4-47c6-4e86-8c80-661aaf081ba2.png)

The pixel stride is greater than the image width in this case.

So I think when we create a bitmap [here](https://github.com/nu-book/zxing-cpp/blob/63523d2306563c0e4bab69ea845995ac8e5728d6/wrappers/android/zxingcpp/src/main/java/com/example/zxingcpp/BarcodeReader.kt#L56), we should remove these padding bytes.

**Comment by axxel** [comment]
Arghh. So `copyPixelsFromBuffer` was wrong in the first place. I did not really check the interface of `Buffer`. It has no notion of rows/strides/etc. A quick look at the doc showed no available method to create a bitmap with a specified rowStride. People seem to copy pixels one by one?!? All the more reason to go along the lines of your PR and deal with the underlying buffer directly. I'll push something that removes the extra copy and fixes this issue tomorrow. Thanks for the support in debugging this!

**Comment by kim-ninh** [comment]
You're welcome.

I just push a commit to add a row stride param in PR and that also fix this issue =)
