### ISSUE TITLE
file 'ZXingReader.cpp' is out of date?

### ISSUE THREAD

**Issue by 2mugik** [nu-book/zxing-cpp#242]
file 'ZXingReader.cpp' is out of date?

**Comment by axxel** [comment]
I don't understand the question. Here is the current HEAD: https://github.com/nu-book/zxing-cpp/blob/master/example/ZXingReader.cpp, which is very much up to date.

**Comment by 2mugik** [comment]
Is this link out of date? 
https://github.com/nu-book/zxing-cpp/blob/master/example/ZXingReader.cpp

**Comment by axxel** [comment]
Our communication is not working: I say "A is true" to which you reply "Is A true?". Please look at my last comment.
