### ISSUE TITLE
How to read multiple barcodes from single image file by using this lib`s python wrapper

### ISSUE THREAD

**Issue by wqh17101** [nu-book/zxing-cpp#243]
zxing_res = zxingcpp.read_barcode((img))
got only one res not a list of res

**Comment by axxel** [comment]
Please see https://github.com/nu-book/zxing-cpp/issues/131#issuecomment-883643453

**Comment by wqh17101** [comment]
but you do not release a python lib via pypi since the version is 1.2.0 now which did not support  this

**Comment by wqh17101** [comment]
![image](https://user-images.githubusercontent.com/26429138/129518553-de83bd22-2ebc-4b3c-ad96-8b93a218228e.png)

**Comment by wqh17101** [comment]
import sys, zxingcpp
from PIL import Image

img = Image.open("test_barcode2.jpg")
results = zxingcpp.read_barcodes(img, zxingcpp.BarcodeFormat.OneDCodes)
if len(results) > 0:
        for result in results:
                print("Found barcode:\n Text:    '{}'\n Format:   {}\n Position: {}"
                        .format(result.text, result.format, result.position))
else:
        print("Could not find any barcode")


with 1.4.0 it works well
