### ISSUE TITLE
When will you release a new verison to support multi-barcodes in one pic

### ISSUE THREAD

**Issue by wqh17101** [nu-book/zxing-cpp#244]
As reply in #243

**Comment by axxel** [comment]
I don't know, yet. I want to make sure I'm happy with the API so I'm not hindered by backward compatibility issues, once it is released.

Is building the python module on your own machine not an option for you?

**Comment by wqh17101** [comment]
it's better for you to release than i setup on my own for i don't know which branch is stable for this issue,maybe master or any other branch
发自我的iPhone


------------------ Original ------------------
From: axxel ***@***.***&gt;
Date: Mon,Aug 16,2021 10:22 PM
To: nu-book/zxing-cpp ***@***.***&gt;
Cc: wqh17101 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [nu-book/zxing-cpp] When will you release a new verison to support multi-barcodes in one pic (#244)

**Comment by axxel** [comment]
Master branch it is.

**Comment by fredtcaroli** [comment]
Any updates on this? I would really like to have multi-barcodes support from a stable release.

**Comment by axxel** [comment]
Counter question: did you try the API as currently implemented in head and if so, do you have any comments? Are you looking for the c++ or the python API?

After some quite months, development has picked up a bit recently. I'll make a new release 'soonish'.

@gitlost are you planning to provide more PRs for the #214 any time soon that would be worth waiting for?

**Comment by gitlost** [comment]
Hi yes am planning to do more PRs for #214, got a bit distracted, will try to speed them up but could spread over a week or so... (will do one now for DataMatrix).

**Comment by axxel** [comment]
@gitlost Please, don't feel rushed! A week more or less is pretty insignificant compared to how long this issue already open... ;).

**Comment by axxel** [comment]
After I finally got the multi-resolution stuff done that I've been working on for quite some time, I'm really planning to do that release 'now'. @gitlost any last minute (as in days) changes you'd like to contribute? (you seem to have been working on interesting stuff ;)).

**Comment by gitlost** [comment]
Hi not really in days, there's the ECI update to Version 2 which could be got PR-ready fairly soonish but it's not worth waiting for I think...

**Comment by axxel** [comment]
Quick update on the current release situation: The multi-resolution work has been paying off according to the findings in https://github.com/nu-book/zxing-cpp/issues/282#issuecomment-1107700255. Especially the 'Close', 'Monitor' and 'Non-compliant' samples stand out. Thanks a lot to @duanqn for his work in testing and debugging this new feature. So depending on my spare time a 1.3 release will happen this week.

**Comment by axxel** [comment]
I build a pre-release 1.3.0 and published it on https://test.pypi.org/project/zxing-cpp/1.3.0/. I'd be thankful for every feedback regarding these builds, especially on windows and macOS.

I'll ping the python users from last year's release: @antoinehumbert @urishab @TransparentLC @timrae. To get you people interested, the 'big' new thing is `read_barcodes()` (plural) that returns a list of all detected symbols. :)

**Comment by urishab** [comment]
Thanks @axxel looks like good work!
Is the read_barcodes already reading multiple barcodes (I personally care about datamatrix) or is this just an interface ATM?

**Comment by axxel** [comment]
@urishab `read_barcodes` is reading multiple symbols _but_ the DataMatrix reader does unfortunately not yet support that (and in fact still requires the one symbol to be intersected by the center-line of the image). I had a quick loot at the missing pieces for that to change and came to the conclusion that it is not trivial and I'd rather not delay the release even further.

But can you confirm that the published test wheels are working in principle for you? What platform are you on?

**Comment by urishab** [comment]
@axxel 
I tested the Win64 wheel and it works for me well.
Python 3.8
Win64

**Comment by axxel** [comment]
To answer the question in the title: today.
