### ISSUE TITLE
Python wrapper raises a vector IndexError

### ISSUE THREAD

**Issue by PhishKliska** [nu-book/zxing-cpp#251]
Following code using zxing python wrapper version 1.2.0 (zxing-cpp==1.2.0), and OpenCV version 4.5.3.56 (opencv-python==4.5.3.56)
```python
import cv2, zxingcpp
img = cv2.imread("bad.png")
result = zxingcpp.read_barcode(img, formats = zxingcpp.barcode_formats_from_str("qrcode"))
```
results in an IndexError when run with the following image:
![bad](https://user-images.githubusercontent.com/87974477/131337658-82205668-8c85-4c9d-a0df-5afde804d776.png)
output:
```
result = zxingcpp.read_barcode(img, formats = zxingcpp.barcode_formats_from_str("qrcode"))
IndexError: vector::_M_range_check: __n (which is 18446744073709095617) >= this->size() (which is 8294400)
```
This image also breaks the [read barcodes web demo](https://nu-book.github.io/zxing-cpp/demo_reader.html).

**Comment by axxel** [comment]
Thanks for bringing this to my attention. This is nice example for a problem that I thought was fixed a long time ago: https://github.com/nu-book/zxing-cpp/blob/16d13bc663ae05c634651314d5ab900af49e438c/core/src/Quadrilateral.h#L95-L101

Note to myself: one possible explanation why being convex is not enough is the fact that the 3 finder + 1 alignment patterns in a QRCode don't form a rectangle.
