### ISSUE TITLE
QR Code not detected (with weird finder pattern)

### ISSUE THREAD

**Issue by kim-ninh** [nu-book/zxing-cpp#258]
Hi, I have this QRCode from my friend. I've try to decode this from original ZXing (java port) and the c++ version of the original repository. Both of them're able to detect the QRCode. Except from the c++ version of current repo.

Any suggestion? 

![z2778174522769_e72ef76edf115d290a14bd06db6273e5](https://user-images.githubusercontent.com/28674990/133991893-b69ee4dd-6f93-47fc-bae6-1c830c31650b.jpg)

**Comment by axxel** [comment]
Well, well. This is clearly not a standards conforming QR Code symbol. It is basically an even more extreme version of the one from #253. You may try the suggested change from there, although I'm skeptical that this will be sufficient to make it work. I can imagine making a change that would even work for this case. But if you would use this code printed on paper and captured with a camera and you rotate the camera only slightly, it will fail to be detected (with all ZXing versions/ports). So my real suggestion is: change the symbol to make it conforming ;).

**Comment by kim-ninh** [comment]
Thank you for the suggestion! I will give it a try. 
Just wonder why some dev has created such a weird QRCode.

**Comment by kim-ninh** [comment]
Unfortunately, this QR Code is generated from an existed mobile app on Google Play Store so I cannot modify its symbol directly (It's some kind of contact link). Could you give me some hints to make it can be recognized? It seems like this line https://github.com/nu-book/zxing-cpp/blob/b6938ec2ae8dae387b4db0d148b57218a0ee8616/core/src/qrcode/QRDetector.cpp#L68 and this https://github.com/nu-book/zxing-cpp/blob/b6938ec2ae8dae387b4db0d148b57218a0ee8616/core/src/qrcode/QRDetector.cpp#L73 but I'm not sure
