### ISSUE TITLE
How to use the library with OpenCV C++?

### ISSUE THREAD

**Issue by ierturk** [nu-book/zxing-cpp#264]
Hi,

Thanks for the great work. I've tested the library from a camera source with Python and OpenCV. However I did not find an example in OpenCV C++. Is there a sample code with OpenCV? I also checked Qt Qml example on Jetson Nano. I need V4L2 controls over camera which is not supported by Qt QML. 

Thanks in advance.
Ibrahim

**Comment by axxel** [comment]
I added some OpenCV example code: https://github.com/nu-book/zxing-cpp/commit/a77fa61fbe6102c39b86e1d4484ddc03a9e314e1. Does that work for you?

**Comment by ierturk** [comment]
Hi @axxel, thanks for the example. It is OK.
