### ISSUE TITLE
Consider Code128 symbols to be potentially GS1-128 by default?

### ISSUE THREAD

**Issue by axxel** [nu-book/zxing-cpp#265]
Given the issue reported [upstream](https://github.com/zxing/zxing/issues/1457), I'm wandering whether or not we should consider changing the default value of `DecodingHints::assumeGS1` to true? Note the complete meaning of the flag would be "assume the code to be GS1-128 iff the first character is \FNC1".

Any opinion on that @gitlost?

**Comment by gitlost** [comment]
Hi sorry, I actually noticed this at the time but then forgot to reply!

I think it should just be removed (i.e. made a no-op) and that FNC1 as the first character should always trigger GS1-128. I can't think of a reason not to.

(I've actually done this in my "[diagnostics2](https://github.com/gitlost/zxing-cpp/tree/diagnostics2)" branch, which also contains a couple of other changes (excluding the diagnostics stuff) - dealing with FNC1 as the second character and implementing #214 Symbology Identifiers - which I haven't got round to making PRs for at the moment.

**Comment by axxel** [comment]
I like that idea. I'll switch the default as suggested first and mark the property as deprecated and then we can happily remove the whole thing after the next release.

It would have also been nice to see the upstream discussion resulting in some insight but it simply died after my hint at this hint. meh.

**Comment by axxel** [comment]
Well, well... my idea was half baked: simply changing the default setting of assumeGS1 to true breaks a few test cases. The issue is the suddenly appearing symbology identifier prefix in the content. After revisiting the # 214 issue and the accompanying upstream issue (including the not yet mentioned background discussion in https://github.com/zxing/zxing/issues/1373) I'm convinced that this one-off prefixing is definitively not the correct default behavior.

My current gut feeling is that we should:
 * deal with symbology identifiers consistently across all barcodes (likely as a metadata return value as in the upstream change),
 * deal with FNC1 handling consistently across all barcodes (which upstream was not prepared to do) and
 * simultaneously drop the assumeGS1 hint.

**Comment by gitlost** [comment]
Totally agree. Prefixing the text (mentioned in the standards) is an old technique for when the scanner output was a stream of bytes. I implemented it as just a `symbologyIdentifier()` method in "Result.h" returning a `const std::string&` in the "diagnostics2" branch... did it for all the symbologies I think, just need to get the PRs ready...
