### ISSUE TITLE
How to include zxing-cpp to project without a shared library

### ISSUE THREAD

**Issue by moellerpm** [nu-book/zxing-cpp#268]
Hello,

I'm facing the following problem. I want to build xzing-cpp from source to integrate it with one of my projects - I don't want to install it to (/usr/...).

This is what my CMakeList looks like:

```
cmake_minimum_required(VERSION 3.0)
project(sample)
set(CMAKE_CXX_STANDARD 20)

set(ZXing_DIR "${CMAKE_CURRENT_SOURCE_DIR}/dependencies/zxing/build")
find_package(ZXing REQUIRED)

add_executable(sample main.cpp ZXingOpenCV.h)

target_link_libraries(sample ZXing)
```

But when I do so I get the following error:

```
CMake Error at dependencies/zxing/build/ZXingConfig.cmake:26 (include):
include could not find requested file:
/home/code/crepo/sample/dependencies/zxing/build/ZXingTargets.cmake

Call Stack (most recent call first):
  CMakeLists.txt:11 (find_package)
```

But why there is no ZXingTargets.cmake file?

I downloaded the source got from the offical repo and did cmake build & make.

What is wrong there, anyone can help?

Thanks

**Comment by huycn** [comment]
I'm not sure to understand what exactly you try to do and where did you checkout zxing-cpp repo relative to your project, but if 'dependencies\zxing' is the location of zxing-cpp repo, to use it directly in your project, try to include the folder instead:
```
cmake_minimum_required(VERSION 3.0)
project(sample)
set(CMAKE_CXX_STANDARD 20)

add_subdirectory (${CMAKE_CURRENT_SOURCE_DIR}/dependencies/zxing/core ${CMAKE_BINARY_DIR}/ZXingCore)

add_executable(sample main.cpp)

target_link_libraries(sample ZXing::ZXing)
```

**Comment by axxel** [comment]
Question: could you solve your problem? If so, please close the github issue.
