### ISSUE TITLE
Would you please release the code of the MultiFormat read?

### ISSUE THREAD

**Issue by QsJack** [nu-book/zxing-cpp#270]
`ZXing::ImageView img_view = image_view_from_mat(img_mat);`
  `std::shared_ptr<ZXing::BinaryBitmap> img_bitmap = std::make_shared<ZXing::HybridBinarizer>(img_view);`
  `ZXing::DecodeHints hints = {};`
  `ZXing::MultiFormatReader multi_reader(hints);`
  `auto res = multi_reader.read(*img_bitmap);`

These are my demo to call MultiFormatReader functions，"image_view_from_mat" is the same as the opencv demo.

But the results is not same as your web demo : https://nu-book.github.io/zxing-cpp/demo_reader.html

Are there something wrong with my demo?

**Comment by axxel** [comment]
Please use the simpler `ReadBarcode` API instead of the `MultiFormatReader` class. Please see the [ZXingOpenCV.cpp](https://github.com/nu-book/zxing-cpp/blob/master/example/ZXingOpenCV.cpp) example.

Please be more specific about what is wrong with the results you are getting.

**Comment by QsJack** [comment]
> Please use the simpler `ReadBarcode` API instead of the `MultiFormatReader` class. Please see the [ZXingOpenCV.cpp](https://github.com/nu-book/zxing-cpp/blob/master/example/ZXingOpenCV.cpp) example.
> 
> Please be more specific about what is wrong with the results you are getting.

OK，Thanks. 

And another question, we compared the old zxing code (https://github.com/zxing/zxing) with this code, the results are not good. We compute the recall by using 200 images.

QRcode : old vs this code = 91.5% vs 84%.

**Comment by axxel** [comment]
"old" vs. this code: The QRCode detector in this c++ implementation is to a large extent a completely different algorithm. From my tests, it detects a lot more compliant codes than the old one. But there are circumstances where the old code could be successful where the new one is not. I'd be happy to look at specific examples and see what I can do to improve the detection further.

If you can identify one or more of your examples that work with the old code but not the new one, please open a new issue and post those examples there.

**Comment by QsJack** [comment]
OK, I will post those examples later. Thanks.

**Comment by QsJack** [comment]
> "old" vs. this code: The QRCode detector in this c++ implementation is to a large extent a completely different algorithm. From my tests, it detects a lot more compliant codes than the old one. But there are circumstances where the old code could be successful where the new one is not. I'd be happy to look at specific examples and see what I can do to improve the detection further.
> 
> If you can identify one or more of your examples that work with the old code but not the new one, please open a new issue and post those examples there.

#275 ，hi, this issue posts some examples.

**Comment by axxel** [comment]
@QsJack Thanks for the samples. I noticed them and did indeed start working on the issue some time ago but I'm currently rather busy with other stuff. I do unfortunately not have a quick fix for you. Will follow up on the other issue when there is news to report.
