### ISSUE TITLE
UPC-E CLASH ISSUE

### ISSUE THREAD

**Issue by NaveenEcon** [nu-book/zxing-cpp#273]
It is observed that when we try to detect the other ONE-D barcodes (like EAN-13,UPC-A,CODE 128 etc) it is found that **UPC-E & EAN-8** were decoding as a false barcodes (I.e. It is not a actual UPC-E/EAN-8 barcode).  
I have observed the detailed working of UPC-E algorithm for the false barcode detection. It was completely passing with the algorithm (zxing library) 

- It has proper Quite zone. 
- Start pattern was perfect. 
- Middle data was decoded with the proper check digit. 
- End pattern was also perfect. 

So this works according to the algorithm, but for us that was actually a wrong data that is being decoded. 
I am attaching the samples that is being decoded as the false barcodes. 
Let me know if any way to eliminate the false detection of these barcodes. 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/96618852/147347446-e052095c-9174-4751-b5a0-6abc78db58d2.png)
Here you can see the UPC-E barcode was decoded inside the some other ONE-D barcode (CODE-39) in the frame.  
This image shows what text was decoding and at what point it was failing and passing.
So here you can see due to 1:1:1 proportion for the START_CODE makes it easier to enter into the detection algorithm (decode middle in zxing lib). So it was completely matching with the algorithm and the ENCODING scheme at some point of time.
Even at times if there was no barcodes in the frame the UPC-E type was being decoded due to black, white transitions in the frame.

More image Samples :
![Screenshot 2021-12-24 134926](https://user-images.githubusercontent.com/96618852/147347402-1556cbc6-6e81-43a7-8cc3-e9da2f389999.png)
![Screenshot 2021-12-24 135022](https://user-images.githubusercontent.com/96618852/147347410-836420aa-bea4-42ac-b369-0b111b843ab4.png)
![Screenshot 2021-12-24 135206](https://user-images.githubusercontent.com/96618852/147347431-baf727e4-2a29-4440-9544-8c7d5e62b4a1.png)

**Comment by axxel** [comment]
I tested current HEAD `ZXingReader` command line utility with all your samples and there was no EAN-8/UPC-E code detected. Could you please also try the current HEAD revision (in case you used an older one for your test)? If you still have the problems, please try to replicate the issue with `ZXingReader`, so that I can observe the issue myself.

Note: you uploaded photos with red dots in them, so they are obviously altered and not exactly what you originally fed your program. That might also be of relevance here.

**Comment by NaveenEcon** [comment]
Thanks for your response axxel,

Actually, I am currently using c++ port of zxing.
I have attached the fresh samples without red dots, kindly check with these samples and let me know,
![upce_479_300](https://user-images.githubusercontent.com/96618852/147435587-552873e2-b987-47f2-8816-b4fd432caf9e.jpg)
![Image](https://user-images.githubusercontent.com/96618852/147435590-a3757d35-0b94-40f4-bca5-f679466deae1.jpg)
![upce_313_210](https://user-images.githubusercontent.com/96618852/147435592-31778ac5-25a5-418d-b541-45c21a51ef42.jpg)
![upce_440_310](https://user-images.githubusercontent.com/96618852/147435595-bae6382f-44e4-47d7-99da-5a7b4506ab64.jpg)

**Comment by axxel** [comment]
Those samples work just as well as the above ones with the red dots. Your last comment makes me wonder whether you are using this project (nu-book/zxing-cpp) at all? Note that this project is "a" (not "the") c++ port of the Java code but there are others that behave completely different, since I rewrote much of the 1D barcode detection code.

**Comment by NaveenEcon** [comment]
These samples were tested with the current (nu-book/zxing cpp). Still I was facing the issue with the UPC-E barcode clash.
Input images :
![in1](https://user-images.githubusercontent.com/96618852/147531655-ca90776a-6fc1-4f6d-a57a-f932ceae37b0.jpg)
![in2](https://user-images.githubusercontent.com/96618852/147531662-ef8b5e41-1f79-4391-b1c6-4aa7ef5bf109.jpg)
![in3](https://user-images.githubusercontent.com/96618852/147531675-5032459c-c6a5-4acc-8c2b-37f0f68ad1f0.jpg)
![in4](https://user-images.githubusercontent.com/96618852/147531677-8549fb29-24c3-4641-a158-0332ce9cb7d6.jpg)
![in5](https://user-images.githubusercontent.com/96618852/147531679-9c6ad4d0-9844-4b63-8bba-cbee484e098b.jpg)

Output images :
![out1](https://user-images.githubusercontent.com/96618852/147531689-b46285c9-9263-47e6-879d-399d3b151795.jpg)
![out2](https://user-images.githubusercontent.com/96618852/147531691-1993ab93-4363-4b2b-8afb-e86f6119a4dc.jpg)
![out3](https://user-images.githubusercontent.com/96618852/147531694-711688d2-3fcb-43bd-bbac-95c08eb55850.jpg)
![out4](https://user-images.githubusercontent.com/96618852/147531696-fac5945c-d729-4840-a928-3649c07e738c.jpg)
![out5](https://user-images.githubusercontent.com/96618852/147531700-4578aaf5-10ac-474f-bd72-ddaaa1e6c5e8.jpg)

**Comment by axxel** [comment]
OK, this is now a different situation. This is the same issue as discussed in #255. See especially my comment https://github.com/nu-book/zxing-cpp/issues/255#issuecomment-918872248 for a potential solution.
