### ISSUE TITLE
Some examples that the old zxing code can parse，but this code can not.

### ISSUE THREAD

**Issue by QsJack** [nu-book/zxing-cpp#275]
#270 this issue. 

Code128 images：
![test_1](https://user-images.githubusercontent.com/10001147/147524380-d083adf3-816c-4587-b423-9f1539d2781e.jpg)
![test_2](https://user-images.githubusercontent.com/10001147/147524408-032e6680-6d5c-480f-8c77-6674540f05f7.jpg)
![test_3](https://user-images.githubusercontent.com/10001147/147524411-c258a01f-07ad-4548-813d-9539816be9b8.jpg)

QRcode images：
![test_1](https://user-images.githubusercontent.com/10001147/147524423-969c5c2c-e46a-4583-b291-aa39fa5d8eda.jpg)
![test_2](https://user-images.githubusercontent.com/10001147/147524431-e0e661a8-379a-4177-b974-aa197b95b794.jpg)
![test_3](https://user-images.githubusercontent.com/10001147/147524438-d967d656-2ae6-432e-b243-84448aa5d046.jpg)

**Comment by QsJack** [comment]
@axxel ~~

**Comment by axxel** [comment]
update: the second qrcode example works now, the rest still does not.

**Comment by axxel** [comment]
I had a quick look at the first three examples and would not have expected the current (or the upstream) code to successfully detect those images. They simply lack resolution/sharpness. I ran all 3 through the current upstream java code (https://zxing.org/w/decode.jspx) and only the second was recognized as a barcode but the reported result was actually wrong (which I would consider worse than failing to detect anything).

Which "old zxing code" are you referring to in your title?

**Comment by QsJack** [comment]
> I had a quick look at the first three examples and would not have expected the current (or the upstream) code to successfully detect those images. They simply lack resolution/sharpness. I ran all 3 through the current upstream java code (https://zxing.org/w/decode.jspx) and only the second was recognized as a barcode but the reported result was actually wrong (which I would consider worse than failing to detect anything).
> 
> Which "old zxing code" are you referring to in your title?

Thanks very much for your constant attention. The "old zxing code" is https://github.com/zxing/zxing  ~~ 

I used the c++ code in my own system. I will check these images again, and give you a new reply later. Thanks.

**Comment by axxel** [comment]
Based on the silence on this issue for quite some time, I consider it not of importance anymore. If you disagree, just let me know.
