### ISSUE TITLE
Adding whitespace impacts detection of datamatrix code

### ISSUE THREAD

**Issue by riedel** [nu-book/zxing-cpp#276]
The following code fails for me reproducibly after adding 200 pixels, however not 100 pixels, for different codes like this one (I can probably produce a test case without an image if needed)

![test](https://user-images.githubusercontent.com/566485/149985488-2b6cfc9b-a2da-42dd-987e-5df295dd43c0.png)

```python
import sys
import zxingcpp
from PIL import Image

img = Image.open(sys.argv[1])
results = zxingcpp.read_barcodes(img)
assert(len(results) > 0)
img2 = Image.new(img.mode, (img.size[0], img.size[1]+100))
img2.paste(img)
results2 = zxingcpp.read_barcodes(img2)
assert(len(results2) > 0)
img2 = Image.new(img.mode, (img.size[0], img.size[1]+200))
img2.paste(img)
results3 = zxingcpp.read_barcodes(img2)
assert(len(results3) > 0)
```

**Comment by axxel** [comment]
This is a duplication of #189. If you can compile the library yourself, you can fix this easily. Please see https://github.com/nu-book/zxing-cpp/issues/189#issuecomment-761121357.

It seems I should find a way to enable that code "somehow". Every once in a while someone stumbles over this. The thing is, that every way to deal with this has its drawbacks and the current situation is simply "how it has always been", so sort of the default without a convincing alternative. :-/

**Comment by riedel** [comment]
Thanks, it would be really good if it was somehow documented, that tryharder is force-disabled.

IMHO, it would be good to make tryharder tri-state: null (depends on decoder), true, false , so that it works if explicitly set.

For me none of the big codes are detected on an A4 sheet, so I will happily pay the price...

**Comment by riedel** [comment]
Did a quick check: works nicely without any performance degradation in my case

**Comment by axxel** [comment]
Thanks for the feedback. Your tri-state idea is interesting. I'll think about it. Good to hear that you could fix your issue.

Any PR to fix issues under cygwin is welcome.
