### ISSUE TITLE
Failure to detect high resolution QRCode symbol

### ISSUE THREAD

**Issue by duanqn** [nu-book/zxing-cpp#282]
Hi,
I tested ZXing-cpp (built from commit ff2da27ffa80bd4fcfb31f2deded36523d298736) on some images and noticed that it could not detect some clear QR codes.
In the below examples, red boxes denote QR code ground truths and blue boxes denote ZXing-cpp decoding results.
![image029_visualize](https://user-images.githubusercontent.com/21275667/153535703-667a0866-af38-4484-b893-7becb41bda0d.jpg)

However, this image is detected correctly:
![image030_visualize](https://user-images.githubusercontent.com/21275667/153535712-1d9873b3-cd7d-47ec-9643-383119c607e6.jpg)

What could be the reason for the different behaviour? Is it because ZXing-cpp does not detect large QR codes?

**Comment by duanqn** [comment]
Original images for reproducing the results:
[images.zip](https://github.com/nu-book/zxing-cpp/files/8045889/images.zip)

**Comment by duanqn** [comment]
Hi @axxel , do you think it would be useful to change the binarizer? I saw three of them (Threshold, GlobalHistogram, Hybrid).
Or maybe I should try reducing the image size by half (each edge) until the shorter edge is less than, say 100 pixels?

**Comment by axxel** [comment]
Changing the binarizer might help in a particular situation. If your input is consistently well 'lit' it might do the trick for you. In general, the multi-resolution approach will be more reliable. I made some progress on an internal solution but am still not done. Reducing the size and trying again is basically the idea. A meaningful threshold is probably closer to 1000 pixels than to 100.

**Comment by duanqn** [comment]
> A meaningful threshold is probably closer to 1000 pixels than to 100.

How is this calculated? Is it like, `edge_size / num_modules < 8`? So if we have 21 modules (QR version 1), then the edge size is about 8*21=168, right?

**Comment by axxel** [comment]
Your calculation makes sense from a theoretical point of few but it would be pretty construed to get exactly this input. My number was merely based on a few real world samples. That said, I like your idea of deriving a threshold instead of just guessing it. The potential downside would be a performance pessimization. If you want to come up with such a constructed example that just fails, we could certainly make use of it in the test samples.

**Comment by duanqn** [comment]
Hi @axxel , I tried to downscale the image and call ZXing multiple times. It does help find more barcodes.
But now I have a problem: how to de-duplicate the results from different resolutions? This is easy for QR codes due to their square shape. For 1D barcodes, I got different recognition results that do not overlap with each other.

**Comment by axxel** [comment]
I'm working on this stuff at the moment (obviously have to solve the same problem). So maybe the best course of action for you at the moment is to wait a 'little longer' until I commit my solution as part of the library. It is a bit more complicated than I anticipated because I feel the need to improve the false-positive detection, so downsampled 1D codes don't get misread.

If you are in a hurry, see the code starting [here](https://github.com/nu-book/zxing-cpp/blob/776ef6178463aca92576fd9bd1339e8d39bb6c0d/core/src/oned/ODReader.cpp#L165).

**Comment by duanqn** [comment]
Sounds great!
Some questions:
1. When I was downscaling the images, I was using OpenCV to resize them. But ZXing does not use external dependencies like OpenCV, so how are you down sampling the images?
2. Instead of resizing the input images, is it possible to re-run binarizer with larger windows and get similar effect? (like 16x16)
3. Can you make this auto-scaling feature optional? For performance reasons people might want to run ZXing without downscaling multiple times.

**Comment by axxel** [comment]
>     1. When I was downscaling the images, I was using OpenCV to resize them. But ZXing does not use external dependencies like OpenCV, so how are you down sampling the images?

With a trivial 3x3 boxing filter. See commit above.

>     2. Instead of resizing the input images, is it possible to re-run binarizer with larger windows and get similar effect? (like 16x16)

That could work but would be more expensive and not be a general solution, i.e. different processing steps would still be required, I believe.

>     3. Can you make this auto-scaling feature optional? For performance reasons people might want to run ZXing without downscaling multiple times.

Most certainly. The default is `off` for the time being. See above commit.

I'd be happy get feedback from you as a beta-tester of this new code. I'd be curious to know if you find samples where it still fails and also to know which threshold values you found to be working for your samples.

**Comment by duanqn** [comment]
Tested on https://boofcv.org/notwiki/regression/fiducial/qrcodes_v3.zip ("detection" part)
ZXing 53ded527ce0cfc88882b91a0a46fd189bc0d3d1b
468 recognized, 764 missed, 4 inserted (recognition result not present in ground truth because the dataset only labels QR codes)
ZXing 53ded527ce0cfc88882b91a0a46fd189bc0d3d1b with OpenCV downscaling
631 recognized, 601 missed, 9 inserted
ZXing 11fc1d88
466 recognized, 766 missed, 3 inserted
ZXing 11fc1d88 with OpenCV downscaling
630 recognized, 602 missed, 8 inserted
ZXing 1e39cbe0505dd3ae25836a123a0498ea90a850d1 set MultiResolutionThreshold to 150
598 recognized, 634 missed, 105 inserted

Filed another issue #314 for the regression between 53ded527ce0cfc88882b91a0a46fd189bc0d3d1b and 11fc1d88.

So two issues:
1. This built-in scaling feature recognizes fewer barcodes compared to external OpenCV downscaling. (598 vs ~630)
2. Many duplicate barcodes in the result.

**Comment by duanqn** [comment]
When I downscale the images with OpenCV, I dedup the results with a simple rule:
If the centroid of a result from low-res is included in a barcode result from high-res layers, remove the result from low-res.
I calculated the centroid with the formula described [here](https://en.wikipedia.org/wiki/Centroid) ("of a polygon").

**Comment by axxel** [comment]
Thanks for the feedback, much appreciated. There was a bug regarding the de-duplication, I took an approach similar to yours to fix it.

The main difference between your and my downscaling is likely the factor. If you have the time, could you please change the value `N` to 2 in https://github.com/nu-book/zxing-cpp/blob/31d547989577d9f29cd4ea8a1f6dc29279cb0ed9/core/src/ReadBarcode.cpp#L59 and see how that changes your statistics?

I'm working with your test data set now to see where I have ideas to further increase the detection rate.

**Comment by axxel** [comment]
With the latest changes, all 40 samples from the 'close' subdirectory work now with `ZXingReader`. Anything else of that sample set of particular interest to you?

**Comment by duanqn** [comment]
@axxel  The latest `HEAD` commit looks pretty good! Even better when I set `N=2`



<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/qiduan/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/qiduan/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



  | Blurred | Bright Spots | Brightness | Close | Curved | Damaged | Glare | High Version | Lots | Monitor | Nominal | Non-compliant | Pathological | Perspective | Rotations | Shadows | Sum
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ZXing e448c0fd | 24 | 23 | 59 | 6 | 29 | 9 | 12 | 2 | 79 | 0 | 51 | 9 | 7 | 24 | 122 | 17 | 473
  | 36.92% | 23.71% | 69.41% | 15.00% | 48.33% | 20.93% | 22.64% | 5.41% | 18.81% | 0.00% | 65.38% | 34.62% | 30.43% | 68.57% | 91.73% | 85.00% |  
ZXing e448c0fd multiRes | 32 | 38 | 64 | 40 | 30 | 14 | 18 | 2 | 118 | 17 | 64 | 20 | 9 | 24 | 123 | 17 | 630
  | 49.23% | 39.18% | 75.29% | 100.00% | 50.00% | 32.56% | 33.96% | 5.41% | 28.10% | 100.00% | 82.05% | 76.92% | 39.13% | 68.57% | 92.48% | 85.00% |  
ZXing e448c0fd multiRes N=2 | 35 | 40 | 63 | 40 | 32 | 15 | 18 | 2 | 150 | 17 | 64 | 21 | 9 | 24 | 126 | 18 | 674
  | 53.85% | 41.24% | 74.12% | 100.00% | 53.33% | 34.88% | 33.96% | 5.41% | 35.71% | 100.00% | 82.05% | 80.77% | 39.13% | 68.57% | 94.74% | 90.00% |  
ZXing e448c0fd OpenCV downscaling | 35 | 40 | 64 | 40 | 32 | 15 | 18 | 2 | 150 | 17 | 64 | 21 | 7 | 24 | 126 | 18 | 673
  | 53.85% | 41.24% | 75.29% | 100.00% | 53.33% | 34.88% | 33.96% | 5.41% | 35.71% | 100.00% | 82.05% | 80.77% | 30.43% | 68.57% | 94.74% | 90.00% |  



</body>

</html>

**Comment by duanqn** [comment]
I'll do a performance evaluation later.

> With the latest changes, all 40 samples from the 'close' subdirectory work now with `ZXingReader`. Anything else of that sample set of particular interest to you?

Would be nice to see improvements on noisy scenarios (not artificially noisy, but close to real life), namely these categories: blurred, damaged, glare, and nominal.

**Comment by axxel** [comment]
Thanks a lot for your help. I'd be interested in this performance comparison. This might affect my opinion about where/if this multi-resolution option should in fact be enabled by default. My current gut-feeling says:
 * disable it on the `ReadBarcode` API, thereby not pessimizing performance in existing use-cases, especially on mobile apps
 * enable it on the new `ReadBarcodes` API
 * enable it in both APIs in the python wrapper

In general, I'm convinced that the library should (mostly) maximize the detection rate in it's default setting and allow to speed up the processing by limiting the search space (see options like `tryRotate`, etc.).

Any feedback regarding this default behavior is very welcome from all interested parties.

**Comment by duanqn** [comment]
Tested on 45cf13287d08b99d6c544643f4059e8da9a3e97f
Compiler: g++ 10.3.0
Ubuntu 20.04; Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz

Dataset: https://boofcv.org/notwiki/regression/fiducial/qrcodes_v3.zip ("detection" part)

Timer was set around `ZXing::ReadBarcodes`, including the cost of constructing `ZXing::ImageView` and `ZXing::DecodeHints`.
The time of `cv::imread` was excluded.
Each image was recognized 3 times and we calculated the average recognition time.

Average time (in milliseconds)
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/qiduan/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/qiduan/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Threshold | N=2 | N=3
-- | -- | --
150 | 55.5462 | 46.5684
500 | 54.6101 | 45.8529
1000 | 51.4354 | 45.3214
65535 | 36.3271 | 36.5701



</body>

</html>


Max time (on the slowest image):

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/qiduan/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/qiduan/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Threshold | N=2 | N=3
-- | -- | --
150 | 325.5244 | 243.776
500 | 321.6267 | 242.5706
1000 | 316.1955 | 240.9633
65535 | 159.9721 | 155.672



</body>

</html>

Plot latency against image area (height times width):

**N=3**

![image](https://user-images.githubusercontent.com/21275667/165432470-9d054b09-94e3-41e3-98e6-20f6c530f486.png)


**N=2**

![image](https://user-images.githubusercontent.com/21275667/165432191-bf389f32-b466-4eef-a18a-e718bc9f968e.png)

**Compare N=2 & N=3**

![image](https://user-images.githubusercontent.com/21275667/165432633-ee1a8a1c-e0c3-43e0-b0cf-55c7cef4834a.png)

**Comment by duanqn** [comment]
> Thanks a lot for your help. I'd be interested in this performance comparison. This might affect my opinion about where/if this multi-resolution option should in fact be enabled by default. My current gut-feeling says:
> 
> * disable it on the `ReadBarcode` API, thereby not pessimizing performance in existing use-cases, especially on mobile apps
> * enable it on the new `ReadBarcodes` API
> * enable it in both APIs in the python wrapper
> 
> In general, I'm convinced that the library should (mostly) maximize the detection rate in it's default setting and allow to speed up the processing by limiting the search space (see options like `tryRotate`, etc.).
> 
> Any feedback regarding this default behavior is very welcome from all interested parties.

@axxel  Is it possible to expose this `N` as a parameter as well? I might want to use `N=2`.

**Comment by axxel** [comment]
Thanks a lot for your thorough performance analysis. What I take from it is the following:
 * the downscale approach is expensive -> it needs to be possible to disable it
 * the factor of 2 is significantly more expensive than 3, while adding very few additional detections
 * I tested all those sample images and found none where a threshold of <500 helps but at least one where 600 was too large

=> 3 and 500 are reasonable default values. They might change in the future.

I believe this issue can be considered fixed or do you have anything else to discuss here?
