### ISSUE TITLE
Merge `assume` DecodeHints options?

### ISSUE THREAD

**Issue by axxel** [nu-book/zxing-cpp#298]
@gitlost just introduced a `assumeITFCheckDigit` property along the lines of `assumeCode39CheckDigit`. His comments indicate that this is actually a GS1 property, making this something like a "GS1 ITF"-Symbol? Would that also be the case for the check digit in the Code39 symbology? If so, should be subsume those two properties into the currently deprecated `assumeGS1` property?

Even if not, I want to question the used term "assume" here, which sounds pretty optional and only hinting at a potential behavior, while what it actually does is forcing a check and fail the detection accordingly. Maybe `validateITFCheckSum`, etc.?

@huycn do you use any of those hints, at all?

(In general, I'd prefer to lower the number of hints that need to be explained and understood and can be selected erroneously.)

**Comment by gitlost** [comment]
Hi, yes, GS1 define what they call "ITF-14" (see GS1 General Specifications version 22, section 5.3), which is 13 digits long + a required check digit (standard GS1 algorithm).

However the ISO standard for ITF, ISO/IEC 16390:2007, says that a check digit is optional, and although the recommended algorithm is the same as GS1's, says that alternative algorithms may be used.

Similarly the ISO standard for Code 39, ISO/IEC 16388:2007, in language very similar to ITF's, says that a check character is optional, and gives a recommended algorithm (mod 43) but says that alternative algorithms may be used. (Code 39 is not used by GS1.)

So I suppose `assumeITFCheckDigit` and `assumeCode39CheckDigit` could be subsumed into an `assumeCheckDigit` hint (or `validate...` etc), but this could be confusing given that other barcodes require a check digit (e.g. Code 128, Code 93).

Also one could argue that there should be a separate hint `assumeITF14` which would check the length as well as the check digit (not that I would)...

I'd agree with "assume" -> "validate" being less ambiguous.

**Comment by axxel** [comment]
Thanks a lot for the detailed background info about the standards. Bottom line:
 * assumeGS1 goes away as planed
 * ITF and Code39 hints stay separated
 * `assume...CheckDigit` -> `validate...CheckSum` makes sense to at least two developers.
