### ISSUE TITLE
DMDetector.traceGaps() endless loop

### ISSUE THREAD

**Issue by bommo1** [nu-book/zxing-cpp#30]
@axxel Thank you for your improvements to the detection of datamatrix codes!

I've found an example where the detector loops forever in the traceGaps() method.
Probably due to rounding in traceStep()  p doesn't change after an iteration.

![frame_00034](https://user-images.githubusercontent.com/32093209/35832779-c69e6f18-0ace-11e8-9301-d89312f549ad.png)

**Comment by axxel** [comment]
Nice: someone is actually using that stuff ;). I reproduced the problem and have an idea what went wrong but have to spent some more time finding the best spot for a missing 'break' in the tracing loop. Hopefully tomorrow...

**Comment by bommo1** [comment]
@axxel Thank you for your prompt response and fix!
Unfortunately I'm still able to reproduce the problem.  

![frame_00266](https://user-images.githubusercontent.com/32093209/35966948-a324e984-0cbf-11e8-8873-344f57c8cb71.png)

**Comment by axxel** [comment]
Too bad... I semi-expected that, in the sense that my fix did not generally make sure this could never happen again. I just did not expect you to come up with another breaking example so quickly ;). I hope I'll come up with something more 'lasting' the next time...

**Comment by axxel** [comment]
Fixed in 5a52422e8275e0ce913a8a945d92f13a973bdf52. Please close the issue if you can confirm that this works for you. I tested it with about 5 other 'dead lock' examples I still have from you.

**Comment by bommo1** [comment]
It works for me too. Thank you!
