### ISSUE TITLE
Exceptions and asserts thrown by QRDecoder

### ISSUE THREAD

**Issue by wejr** [nu-book/zxing-cpp#300]
We're trying to find QR codes in the camera image. The attached images cause 3 different detection errors. 

We try to load the images as follows ZXingReader.exe -format QRCode qrcode_1280x960_bw_out_of_range.png.  With the -fast switch the detection does not fail.

For the image qrcode_1280x960_bw_out_of_range.png (first image) the exception std::out_of_range is thrown from std::vector (it is visible when loading from the web https://nu-book.github.io/zxing-cpp/demo_reader.html)

The other 2 images are causing asserts.

![qrcode_1280x960_bw_out_of_range](https://user-images.githubusercontent.com/7448633/156545113-d77ac09c-d325-4d17-a42b-f496c3440087.png)

![qrcode_1280x960_bw_direction](https://user-images.githubusercontent.com/7448633/156545109-461e0e32-655b-49ac-a8dd-664142b52c2e.png)

![qrcode_1280x960_bw](https://user-images.githubusercontent.com/7448633/156545115-9b263b40-0883-4222-a33f-32b1751d7c66.png)

**Comment by axxel** [comment]
I could not reproduce the issue with the first image. Did you try with HEAD or the latest release?

The other two images work now.

**Comment by wejr** [comment]
You're right, the problem with the first image was solved in #267 and #251. Thank you for the quick solution

**Comment by wejr** [comment]
I found another images that causes the same assert (assert(cur.isBlack());)

![qrimage_1280_960_assert_1_bw](https://user-images.githubusercontent.com/7448633/156761111-08fceee4-eceb-4c06-97e9-9705e571799f.png)

![qrimage_1280_960_assert_bw](https://user-images.githubusercontent.com/7448633/156761113-13446d55-ae94-450d-9d32-30b464e48677.png)

**Comment by wejr** [comment]
I'm sorry, but the problem still persists, I have attached more pictures

![qrcode3_1280x960_0_bw](https://user-images.githubusercontent.com/7448633/158370303-91734b90-abe5-4e5d-850b-ed99c152a395.png)
![qrcode3_1280x960_1_bw](https://user-images.githubusercontent.com/7448633/158370307-8b720d08-cd6e-4c1b-b673-21b798069009.png)

**Comment by axxel** [comment]
The floor part of your samples is almost random -> not very well tested with current sample set. Thanks for bringing it to my attention. If you have more, bring it on! :)

**Comment by wejr** [comment]
The last modification seems to be stable, I'll let the test run for a few more days. For now, thank you
