### ISSUE TITLE
ZXing-cpp fails to detect some really clear 1D barcodes

### ISSUE THREAD

**Issue by duanqn** [nu-book/zxing-cpp#303]
Hi,
I was trying to recognize [this image](https://accuware-inc.com/wp-content/uploads/2016/07/H-and-H.png) with ZXing-cpp. The image contains several obvious barcodes, and they look like Code 39 or its variants. However, ZXing-cpp cannot detect any of them.
Can anyone help me understand the reason?

ZXing-cpp was built from current HEAD version 53ded527ce0cfc88882b91a0a46fd189bc0d3d1b.

To prevent broken links, the image is here:
![image](https://user-images.githubusercontent.com/21275667/159835622-e5337e50-1bd5-4e37-9832-33f19d6d4419.png)

**Comment by axxel** [comment]
I tried several online barcode readers and none of them were able to detect a known barcode. Do you have an idea what type of barcode symbology this is supposed to be?

**Comment by duanqn** [comment]
I had the same question. I tried to "reverse-engineer" the barcode with Zint, the image looks close to Code39.
I generated "P581-40-510H" with Zint, it looks like the barcode in this image but there are still some differences.

![image](https://user-images.githubusercontent.com/21275667/160582287-756b37f4-dbd3-47d3-ba85-baac96e9a87d.png)

**Comment by axxel** [comment]
I see what you mean. I'd also conclude that this is supposed to be Code39 then. But it obviously is broken. I assume there are issues with the rendering. Maybe the output resolution is simply not enough.

**Comment by gitlost** [comment]
Yes the barcodes appear to be Code39 with adjoining bars at certain intervals fused together - what is known as "pixel grazing" - see Terry Burton's presentation slide [12](http://slides.com/terryburton/barcode-writer-in-pure-postscript#/12).
