### ISSUE TITLE
include\ZXing\ImageView.h(84): error C2589: Illegal token on right side of (build for windows and vs2019)

### ISSUE THREAD

**Issue by shanliu** [nu-book/zxing-cpp#305]
zxing-cpp-lib\include\ZXing\ImageView.h(84): error C2589: “(”:“::”右边的非法标记 (编译源文件 ext\zxing_cpp\zxing_cpp_lib.cpp)
zxing-cpp-lib\include\ZXing\ImageView.h(84): error C2062: 意外的类型“unknown-type”  (编译源文件 ext\zxing_cpp\zxing_cpp_lib.cpp)
zxing-cpp-lib\include\ZXing\ImageView.h(84): error C2059: 语法错误:“)” (编译源文件 ext\zxing_cpp\zxing_cpp_lib.cpp)
zxing-cpp-lib\include\ZXing\ImageView.h(85): error C2589: “(”:“::”右边的非法标记 (编译源文件 ext\zxing_cpp\zxing_cpp_lib.cpp)
zxing-cpp-lib\include\ZXing\ImageView.h(85): error C2062: 意外的类型“unknown-type”  (编译源文件 ext\zxing_cpp\zxing_cpp_lib.cpp)
zxing-cpp-lib\include\ZXing\ImageView.h(85): error C2059: 语法错误:“)” (编译源文件 ext\zxing_cpp\zxing_cpp_lib.cpp)
zxing-cpp-lib\include\ZXing\ImageView.h(86): error C2589: “(”:“::”右边的非法标记 (编译源文件 ext\zxing_cpp\zxing_cpp_lib.cpp)
zxing-cpp-lib\include\ZXing\ImageView.h(86): error C2062: 意外的类型“unknown-type”  (编译源文件 ext\zxing_cpp\zxing_cpp_lib.cpp)

```
ImageView cropped(int left, int top, int width, int height) const
	{
		left   = std::max(0, left);
		top    = std::max(0, top);
		width  = width <= 0 ? (_width - left) : std::min(_width - left, width);
		height = height <= 0 ? (_height - top) : std::min(_height - top, height);
		return {data(left, top), width, height, _format, _rowStride, _pixStride};
	}
```
change to,fix it.
```
ImageView cropped(int left, int top, int width, int height) const
	{
		left   = (std::max)(0, left);
		top    = (std::max)(0, top);
		width  = width <= 0 ? (_width - left) :( std::min)(_width - left, width);
		height = height <= 0 ? (_height - top) : (std::min)(_height - top, height);
		return {data(left, top), width, height, _format, _rowStride, _pixStride};
	}
```

**Comment by duanqn** [comment]
This is unexpected. Did you have something like `#define max(a, b)` and `#define min(a, b)` in your other files? If you do, remove those macros.

**Comment by shanliu** [comment]
i can't remove the macros.define in windows.h

**Comment by duanqn** [comment]
The fix is simple: undefine them before including ZXing headers.
```
#pragma push_macro(min)
#undef min

#pragma push_macro(max)
#undef max

#include <Your ZXing Header Name Here>

#pragma pop_macro(max)
#pragma pop_macro(min)

```

`push_macro` and `pop_macro` may not be supported by all compilers, but they work with MSVC (https://docs.microsoft.com/en-us/cpp/preprocessor/push-macro?view=msvc-170) and gcc.

**Comment by axxel** [comment]
Making sure that `NOMINMAX` is defined as a preprocessor token in your build environment or via `#define` before including `Windows.h` is also an option.

**Comment by shanliu** [comment]
thanks.
