### ISSUE TITLE
 How to install Zxing CPP (C++) on RaspberryPi

### ISSUE THREAD

**Issue by Steven-YiTseWu** [nu-book/zxing-cpp#306]
As the title, I want to build an environment of ZXing C++ on Raspberry Pi.
According to the https://github.com/nu-book/zxing-cpp instruction, I try to build it.
However, I face some problems, like Cmake error. (Not found std, fmt)
Anyone has the experience that build an environment of ZXing C++, and compile programs successfully? Hope you can share the steps, thanks!!!

**Comment by Steven-YiTseWu** [comment]
Sure. Thank you for your reply
The cmake errors in the below url. I asked the same question yesterday on StackOverFlow.
[](https://stackoverflow.com/questions/71648530/how-to-install-zxing-cpp-c-on-raspberrypi)

**Comment by axxel** [comment]
The problem with missing `std::is_integral_v` hints at an issue with your compiler setting. The code needs to be compiled with c++17 support. But that is required in the core libraries CMakeLists.txt. It could be helpful if you made a verbose make call and provide the complete compiler command line for the compilation of the `BarcodeFormats.cpp` translation unit.

Note: the errors you posted on stackoverflow are not cmake but compiler errors.

**Comment by Steven-YiTseWu** [comment]
Thank you, I have built ZXing successfully.     
![截圖 2022-03-29 下午7 58 17](https://user-images.githubusercontent.com/44743933/160606168-2854dcdf-19e1-4fba-8c48-e3cb811f4c35.png)
However, I face compile error.  I have no idea how to use Zxing library to develop programs.
(I'm a noob about it)
Could you give me some ideas, please?

**Comment by axxel** [comment]
I know nothing about about Geany IDE. I suggest you look at the ZXingReader example application and start from there.

**Comment by axxel** [comment]
Since your original issue (see title) is solved, I close this.
