### ISSUE TITLE
How to use the new version of decoding library to decode DM code on vs2015

### ISSUE THREAD

**Issue by wanweitong** [nu-book/zxing-cpp#315]
I'm having trouble applying the latest version of the ZXing library. We can only use vs2015 c++11 standard to report errors when generating lib files. Is there any way to use the latest version of the ZXing library under vs2015 c++11 standard?
Under the example folder, you can only get pictures from local files. Now I want to send them to the decoder directly in mat format. Could you tell me how to use them?

**Comment by axxel** [comment]
> Is there any way to use the latest version of the ZXing library under vs2015 c++11 standard?

No. As our Readme.md states: the minimum Visual Studio version to build the library is  "VS 2019 16.8"

> Under the example folder, you can only get pictures from local files. Now I want to send them to the decoder directly in mat format. Could you tell me how to use them?

If you mean OpenCVs `Mat` class, please look [here](https://github.com/nu-book/zxing-cpp/blob/master/example/ZXingOpenCV.h).

**Comment by axxel** [comment]
If you don't have any more questions/comments, please close the issue.
