### ISSUE TITLE
Support for micro QR codes

### ISSUE THREAD

**Issue by corbers** [nu-book/zxing-cpp#319]
I have an implementation of a micro QR code detector and decoder which I'd like to contribute to the project.  The implementation is written in C++ but uses the style of the original C++ port from the Java library, e.g. Ref<BitMatrix> etc.  I'm willing to spend the time to change the code so that it's more in keeping with the nu-book version of ZXing but I need some guidance on a few things 😄 
1. The current implementation is separate from the QR code implementation.  It resides in a different folder in the source tree and uses a different value in the BarcodeFormat enum.  My preference is that the same approach is used when I add the code to this library.  It would remove any risk from making code changes to the existing QR code implementation.  However, I appreciate that micro QR codes are part of the ISO standard and so maybe they should be part of the QR code implementation.
2. How would you like me to contribute the code?  I could provide a single pull request but that might be too much to review when I'm sure there will be some code we will need to discuss. 😉 I could split the code into detector and decoder and provide unit tests for each.  Maybe you have some suggestions?
3. I don't have an encoder.  Is this required to add micro QR code support to the project?

Thanks.

**Comment by gitlost** [comment]
Hi I'll let axxel or others answer those questions but could you share your implementation on github as it stands? It would be very useful to me (testing Zint).

**Comment by corbers** [comment]
> Hi I'll let axxel or others answer those questions but could you share your implementation on github as it stands? It would be very useful to me (testing Zint).
@gitlost The current implementation is part of a larger project and so it makes more sense to start the port to this project and share my progress in a branch.
@axxel Thanks for the reply.  I'll begin work on the detector and some unit tests and push them to a branch for you to look at.

**Comment by corbers** [comment]
I have a working micro QR code detector now.  I've adapted the existing code that I had so that it compiles with the nu-book ZXing and I've added some unit tests as well.  The code can be found here https://github.com/kurzdigital/zxing-cpp/tree/add_micro_qr_code  Feel free to have a look and we can discuss what I've added.  Do you want me to create a PR for this branch now?

I'm going to start adding the decoder to the same branch but I'm open to splitting detector and decoder into separate branches if that makes things more manageable.

**Comment by axxel** [comment]
I noticed it yesterday already and did have a quick glance. Questions:
* do you care about keeping the separate commits in the history? If so, are you prepared to engage in history rewriting (like interactive git rebase) to make changes to these individual commits?
* if not, we can simply pile up commits and I'll squash them before merging (definitively less work)
* do you have a setup where you can use clang-format?

I think we should start with this as a PR before adding more stuff, reduces the risk of me annoying you with too many change requests. ;). By the way: please just let me know anytime if you feel like having spent enough time on this. I can always make changes down the line myself if I deem them important.

**Comment by corbers** [comment]
> do you care about keeping the separate commits in the history? If so, are you prepared to engage in history rewriting (like interactive git rebase) to make changes to these individual commits?

I'm prepared to make changes to the history.  99% of the development work was done in another repository which we have the history for.  What would you like me to do?

> do you have a setup where you can use clang-format?

I have VS 2019 which supports clang-format but if necessary I can use CLion if VS is not formatting the code correctly.  I don't see a clang format file in the project though.

A PR soon is a good idea. 😄

**Comment by axxel** [comment]
> I'm prepared to make changes to the history. 99% of the development work was done in another repository which we have the history for. What would you like me to do?

Alright: then please submit the PR and I'll make some comments and we take it from there.

>  I don't see a clang format file in the project though.

That is correct. I have one lying around that I'm using for years now but have never felt confident enough with it to actually apply it globally. Nonetheless, it mostly reflects the recently applied style and should be a very good base-line. I just pushed it...

**Comment by axxel** [comment]
implemented in #324
