### ISSUE TITLE
Decoding multiple CODE-128 barcodes

### ISSUE THREAD

**Issue by glitchyordis** [nu-book/zxing-cpp#328]
![download](https://user-images.githubusercontent.com/99534415/166852507-47d0c1b8-a57d-4053-8f69-1c3c78938101.png)

Hi, I've attempted to decode a few barcodes (CODE-128 ) in a single picture with different pictures. However, only the last one is returned. Is it possible to decode multiple barcodes with zxing-cpp or I'm doing something incorrectly?

my code (using python wrapper):
import zxingcpp
zxingcpp.read_barcode(img).text

output:
33556677

**Comment by axxel** [comment]
Wrong function used. Please see sample code here: https://github.com/nu-book/zxing-cpp/blob/master/wrappers/python/README.md
