### ISSUE TITLE
Building from zip and other questions

### ISSUE THREAD

**Issue by Chris-R-R** [nu-book/zxing-cpp#331]
Hi I just downloaded the zip onto a Windows system and tried to build with CMake but I get an error:

CMake Error at C:/Program Files/CMake/share/cmake-3.23/Modules/ExternalProject.cmake:2540 (message):
  error: could not find git for clone of stb-populate
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.23/Modules/ExternalProject.cmake:3640 (_ep_add_download_command)
  CMakeLists.txt:23 (ExternalProject_Add)

I guess this is trying to use git to download additional dependencies but I do not have git installed on my system.

* Should the code not be buildable directly from the zip?
* Can I configure it to not need additional libraries?
* Is this the only ZXing C++ port that can actually generate QR-codes? It seems that the other options only support reading QR-codes.
* Does the inclusion of Qt code under the textcodec folder mean that this library in practice falls under the LGPL license rather than the Apache 2.0 license of the original ZXing?

Thanks

**Comment by axxel** [comment]
> I guess this is trying to use git to download additional dependencies but I do not have git installed on my system.

Yes.

> Should the code not be buildable directly from the zip?

Yes, but depending on your build options and your available system libraries, you may need additional stuff, like `stb` in this case. If you disable the build of the tests and the examples, you should be able to build without requiring stb or git (have not tested that in while). See the `BUILD_...` cmake options.

> Is this the only ZXing C++ port that can actually generate QR-codes? It seems that the other options only support reading QR-codes.

That I don't know.

> Does the inclusion of Qt code under the textcodec folder mean that this library in practice falls under the LGPL license rather than the Apache 2.0 license of the original ZXing?

That is a good question. Please also have a look at https://github.com/nu-book/zxing-cpp/blob/master/LGPL_EXCEPTION.Qt. Maybe @huycn can also provide some insight, as he originally incorporated that code?

**Comment by Chris-R-R** [comment]
I can confirm I can avoid the need to download additional dependancies by runningcmake -DBUILD_READERS=ON -DBUILD_WRITERS=ON -DBUILD_SHARED_LIBS=ON =DBUILD_UNIT_TESTS=OFF -DBUILD_BLACKBOX_TESTS=OFF -DBUILD_EXAMPLES=OFF -G "Visual Studio 16 2019" -A Win32 ..

The visual studio solution and project files are created but I get the following output:

 Performing Test COMPILER_NEEDS_FLOAT_STORE - Failed

Is this anything to worry about? I have CMake 3.23.1
