### ISSUE TITLE
Cast my own flags into a ZXing::Flags

### ISSUE THREAD

**Issue by 3unjee** [nu-book/zxing-cpp#341]
Greetings zxing maintainers,

I've decided to go with my own `formats` enum flags that I convert in time into a ZXing::BarcodeFormats with the following:
`hints.setFormats(static_cast<const ZXing::BarcodeFormats> (formats));`

However, it seems the ZXing::Flags implementation will not let me do that unless the following becomes public:
`constexpr inline Flags(Int other) : i(other) {}`

Could it be allowed in a subsequent releases ?

**Comment by axxel** [comment]
That constructor is deliberately private to supply type safety. This seems to be a very special use case you are having. What about you `static_cast` or `reinterpret_cast` your `formats` into a `BarcodeFormat`? There is a public constructor for that which does exactly the same thing.

**Comment by 3unjee** [comment]
I'm currently using the Qt framework, without hacking the private headers it seems you'd have to do the following (from https://github.com/scytheStudio/SCodes):
```
ZXing::BarcodeFormats SCodes::toZXingFormat(SBarcodeFormats formats)
{
    ZXing::BarcodeFormats zXingformats;

    int formatEnumIndex = SCodes::staticMetaObject.indexOfEnumerator("SBarcodeFormat");
    QMetaEnum sBarcodeFormatEnumMeta = SCodes::staticMetaObject.enumerator(formatEnumIndex);

    for (int i = 0; i < sBarcodeFormatEnumMeta.keyCount(); ++i) {
        const auto key = sBarcodeFormatEnumMeta.key(i);
        const auto value = sBarcodeFormatEnumMeta.keyToValue(key);
        const auto enumValue = static_cast<SCodes::SBarcodeFormat>(value);
        if (formats.testFlag(enumValue)) {
            zXingformats |= toZXingFormat(enumValue);
        }
    }

    return zXingformats;
}
```

**Comment by axxel** [comment]
In that case I'd like to point you to or "own" Qt wrapper code in the examples directory. See also the lengthy #128 for how this might soonish be morphed into a 'real' qt library.

There is particularly [this line](https://github.com/nu-book/zxing-cpp/blob/a8629e04bc0a5369227f035613dc960ae9298984/example/ZXingQtReader.h#L292) showing exactly what I meant earlier.

**Comment by 3unjee** [comment]
Thank you for theses ressources, indeed casting works fine for the ZXing::BarcodeFormat enum in itself, not the flags.

Yes this framework works suprisingly well in conjunction with the QtMultimedia module. Even though the API kept evolving during Qt5 lifetime and now Qt6.

**Comment by axxel** [comment]
> Yes this library works suprisingly well in conjunction with the QtMultimedia module. Even though the API kept evolving during Qt5 lifetime and now Qt6.

With 'this library' you mean SCodes or zxing-cpp?

**Comment by 3unjee** [comment]
zxing-cpp 👌
