### ISSUE TITLE
Linker error with `MultiFormatWriter`

### ISSUE THREAD

**Issue by Gilbert2019** [nu-book/zxing-cpp#342]
compilation hello everyone! 
Other functions can be called. When the zxing library is used to generate barcode, it will prompt that multiformatwrite:: encode cannot be parsed. What is the reason?
`DecodeHints hints;
hints.setCharacterSet("UTF8");
MultiFormatWriter writer(BarcodeFormat::CODE_128);
writer.setEncoding(CharacterSet::UTF8);
int margin = 0, eccLevel = 5, width = 200, height = 200;
writer.setMargin(margin);
writer.setEccLevel(eccLevel);
std::wstring text = L"good";
auto matrix = writer.encode(text, width, height);`
LNK2019	"public: class ZXing::BitMatrix __cdecl ZXing::MultiFormatWriter::encode(class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,int,int)const " (?encode@MultiFormatWriter@ZXing@@QEBA?AVBitMatrix@2@AEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@HH@Z)
![MultiFormatWriter encode Cannot resolve](https://user-images.githubusercontent.com/51197749/173168891-4a1aa2a3-8d04-4013-829a-bd2a524f9485.png)

**Comment by axxel** [comment]
This is a linker error. I see two most likely reasons for that:
 1. you simply did not link libXing at all
 2. you build the library without writer support (see cmake option `BUILD_WRITERS`)

**Comment by Gilbert2019** [comment]
dear axxel:

**Comment by Gilbert2019** [comment]
dear axxel:
That's what you said. The problem has been solved. Thank you very much!

**Comment by Gilbert2019** [comment]
dear axxel:
That's what you said. The problem has been solved. Thank you very much!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nu-book/zxing-cpp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月11日(星期六) 下午2:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nu-book/zxing-cpp] Linker error with `MultiFormatWriter` (Issue #342)





 
This is a linker error. I see two most likely reasons for that:
  
you simply did not link libXing at all
 
you build the library without writer support (see cmake option BUILD_WRITERS)
