### ISSUE TITLE
pdf147 write result correct ness

### ISSUE THREAD

**Issue by yaozhaoxu** [nu-book/zxing-cpp#343]
Hi.I use writer to encode pdf147 code, the result is wrong.The other format code writers' result is right. the pdf147 seems wrong.my setting is width 700, height 300，text is 123456789,Marin 10

**Comment by axxel** [comment]
With the command line `ZXingWriter -size 700x300 -margin 10 pdf417 123456789 pdf417.png` I get the attached output and that seems to be a perfectly valid PDF417 symbol. What is your specific issue?
![pdf417](https://user-images.githubusercontent.com/1038346/173547642-027e71ab-6066-4c01-a936-0855b7116dcb.png)

**Comment by axxel** [comment]
The problem is the line
```
Mat tests = Mat(height,width,CV_8UC1,(unsigned char*)buffer);
```
It is not guaranteed that you get exactly `widthxheight` pixels back. You need to write:

```
Mat tests = Mat(bitmap.height(),bitmap.width(),CV_8UC1,(unsigned char*)buffer);
```

**Comment by yaozhaoxu** [comment]
thinks
