### ISSUE TITLE
Sensitivity to cropping

### ISSUE THREAD

**Issue by hgaiser** [nu-book/zxing-cpp#344]
For my task I am limited in the available space for a marker (roughly 1cm x 1cm only). I am running some tests to see how viable different markers are at this size, in combination with the required workspace area. Below is a crop of the area where I am expecting markers to be found:

![cropped2](https://user-images.githubusercontent.com/716138/174255093-755dc01b-2ef0-4e58-986e-5f049430dbcc.png)

From this image, 10/10 markers are correctly detected. If I use the exact same image but crop it further (so pixel density and information should remain the same) it will sometimes detect less markers than before. For example on this crop:

![cropped](https://user-images.githubusercontent.com/716138/174255128-47b3ab15-89f9-4d50-9b2b-a77e11fbcd7b.png)

It didn't detect markers 2 and 6 and it decoded marker 1 as 10.

Am I close to the limits of what this algorithm can detect? Or is there something strange going on here? Any information is appreciated, because it would help me decide the direction for my project :).

Some extra information: I am using Micro QR code because in my (brief) experiments it seemed to produce the most stable results. I used data matrices before but the detection rate and cropping sensitivity was significantly worse there. What I require is to identify roughly 20 different markers.

**Comment by axxel** [comment]
Interesting problem. There are three things I'd like to say:
 1. these are all invalid MicroQRCode symbols because they don't have a 2 modules wide quite zone (the black border is too close to the symbols (I believe, if you changed that it would work).
 2. I don't know why the cropping makes any difference here. That is weird.
 3. I will try to change something, such they hopefully work even though they are not valid symbols.

**Comment by hgaiser** [comment]
Ahh interesting! I didn't know the quiet zone had to be two modules wide, I will surely try that out. I will probably be checking this again next Thursday, I will let you know what I find 👍 . Thank you for the reply.

**Comment by oehhar** [comment]
Am 18.06.2022 um 13:06 schrieb axxel:
> Interesting problem. There are three things I'd like to say:
> 
>  1. these are all invalid MicroQRCode symbols because they don't have a
>     2 modules wide quite zone (the black border is too close to the
>     symbols (I believe, if you changed that it would work).

AFAIK, the standard quiet zone is 3 modules, at least for QR-Code. That 
is often seen as a disadvantage compared to DMRE/DM, as the quiet zone 
is only one pixel.

Enjoy,
Harald

**Comment by hgaiser** [comment]
Seems to be 4 for QR and 2 for MicroQR:

https://www.qrcode.com/en/codes/microqr.html :
> Furthermore, QR Code requires at least a four-module wide margin around a symbol, whereas a two-module wide margin is enough for Micro QR Code.

**Comment by axxel** [comment]
My commit fixes the specific sample you provided. But does not really address the issue that a different cropping made a difference. If you find some samples that are still problematic, just reopen the issue.

**Comment by hgaiser** [comment]
Ah that's great! I just tested it on the images that I have available and it seems completely stable now, even though the quiet zone is not correct in those images.

Is it possible that the same fix needs to be applied for data matrices? I had an earlier test where I also recorded an Aztec marker and a DataMatrix, where the DataMatrix wasn't detected but after a crop it was detected.

The full image (only MicroQR was detected) :
![all_markers_no_light](https://user-images.githubusercontent.com/716138/174444266-d6871d21-f5ce-4342-bb84-c26020de1277.png)

The cropped DataMatrix (which is detected) :
![data-matrix-crop](https://user-images.githubusercontent.com/716138/174444289-f9e82fd0-4c92-471a-8ed5-3f24cc769f1e.png)

I couldn't get the Aztec marker to work at this scale, even after removing the black border:
![aztec-marker-crop](https://user-images.githubusercontent.com/716138/174444582-d8a5913b-8353-4852-b0aa-c853efd40f81.png)

**Comment by axxel** [comment]
The datamatrix dependency on the symbol position is a known (and semi fixed) issue. See [this comment](https://github.com/nu-book/zxing-cpp/issues/189#issuecomment-761121357) for a solution. It might still make sense to stick with MQR codes, let me know what you find...

The Aztec detector is simply very limited in it's capabilities. This needs a completely different algorithmic approach to make it work with non-trivial real-world input. I suggest not to use Aztec symbols if you can control it.

**Comment by de-vri-es** [comment]
> Note: while the above mentioned fix/workaround for DataMatrix allows you to decode a symbol anywhere in the image, it will still only find 1 symbol per image. So that will not work for you, either (in case you have not noticed, yet...).

Yes, for now we're working around that by filling them with black and repeating the detection until nothing more is found :)

**Comment by axxel** [comment]
@de-vri-es are you somehow connected with @hgaiser or just accidentally having the same issue? If you two are working on the same problem, then why do you not use MicroQRCodes that don't have this problem?

**Comment by axxel** [comment]
Would you be interested in a library that supports scanning multiple DM symbols if that support was dependent on a c++20 compiler? The solution of this problem seems to lend itself very well to coroutines and if that would help you, I would be interested in giving it a try (would my first ever coroutine usage ;)).

**Comment by de-vri-es** [comment]
A C++20 compiler is no problem for us. Although we're integrating it with a Rust application in the end, but I think we can probably manage to use co-routines.

Although for us MicroQR is probably also good. We just want to get the codes as small as possible.

**Comment by axxel** [comment]
> Although for us MicroQR is probably also good. We just want to get the codes as small as possible.

Then DM should be preferable, as it has a higher data density. On the other hand, even with native Multi-DM support, the detection of MQR codes will be a lot faster.

**Comment by axxel** [comment]
Did you have a chance to try out my latest c++20 based fix for your DM issue?

**Comment by hgaiser** [comment]
Ah thanks for the reminder, I didn't get a notification that a commit was referencing this issue it seems. I can only test this in a limited setting at the moment, but the result has improved. I tested on the same image as [before](https://github.com/nu-book/zxing-cpp/issues/344#issuecomment-1159480743), with C++17 only the MicroQR code was detected, with C++20 enabled the results are:

```
Text:       "4"
Utf8ECI:    "]d4\0000264"
Bytes:      34
BytesECI:   5D 64 34 34
Format:     DataMatrix
Identifier: ]d1
Content:    Text
HasECI:     false
Position:   2210x378 2210x436 2152x436 2152x378
Rotation:   90 deg
IsMirrored: false

Text:       "4"
Utf8ECI:    "]Q2\0000264"
Bytes:      34
BytesECI:   5D 51 32 34
Format:     MicroQRCode
Identifier: ]Q1
Content:    Text
HasECI:     false
Position:   2211x1558 2211x1615 2154x1615 2154x1559
Rotation:   90 deg
IsMirrored: false
EC Level:   L

Text:       ""
Utf8ECI:    ""
Bytes:
BytesECI:
Format:     DataMatrix
Identifier:
Content:    Text
HasECI:     false
Position:   0x0 0x0 0x0 0x0
Rotation:   0 deg
IsMirrored: false
Error:      FormatError
```

Not sure what the second DataMatrix is about, it has no known position either. Blocking out the Aztec marker made no difference.

I can test this more extensively tomorrow, so I'll let you know :). Regardless, thank you for all the effort!

**Comment by axxel** [comment]
In case you did not receive the update again. I fixed the spurious empty DataMatrix detection. Looking forward to you feedback.

**Comment by hgaiser** [comment]
> In case you did not receive the update again. I fixed the spurious empty DataMatrix detection. Looking forward to you feedback.

Thanks for the message, I don't think Github sends notifications for referenced commits so I indeed didn't get it again.

The results have significantly improved, I have seen missed detections in only a few positions. One of them is the following:

![raw](https://user-images.githubusercontent.com/716138/176656742-2d235537-29ef-4a7b-adf3-19aa78906f5f.png)

Which results in these detections:
![detected](https://user-images.githubusercontent.com/716138/176657216-53af773c-a304-42a7-b5fd-2c883eabebf1.png)

**Comment by axxel** [comment]
Thanks for further testing this. After I got the 1.4 release out I had another look at this and just pushed a fix for the remaining issue. It does now detect all 10 symbols. If you find more issues, keep them reports coming ;).

**Comment by axxel** [comment]
Your theory sounds about right. If this is not a one-off random situation but something that you expect I suggest a preprocessing step that simply replaces all saturated while pixels with a mid-gray, that or something along those lines should do the trick.

**Comment by hgaiser** [comment]
Yep we're doing something similar now, we're stretching the contrast so
that the gray of the marker becomes as white as the background. That seems
to have solved our issue. Thanks for confirming!
