### ISSUE TITLE
More API cleanup for 2.0 (community feedback requested)

### ISSUE THREAD

**Issue by axxel** [nu-book/zxing-cpp#345]
Thinking about what else I could break now while I'm at it (besides #338):

**Error reporting via `DecodeStatus Result::status()`**

There are two things I don't like about that:
 1. The name `status` and
 2. The fact that the information `NotFound` is communicated from 'inside' a result which I like to view as a representation of a 'found' symbol, which is a contradiction.
 
Upstream Java uses exceptions to communicate both any errors and the not-found condition. @huycn did not go that way for good reasons. The `ReadBarcodes` function does not need that at all as the returned list is then simply empty. The `ReadBarcode` function should rather return a `std::optional<Result>` from my today's perspective (which was not an option 5 years ago with c++11). The 'native' behavior on both android and python can/should be to return a `null`/`none` object in that case.

In terms of error reporting in general I'd like to suggest the following hopefully consistent approach:
 * not found: return empty list / empty optional (or maybe 'empty' `Result` if the API break is not worth it, see below)
 * format/checksum error: reported per symbol/result in new member like `Result::error`
 * runtime error: throw exception (already happening today, even if not made obvious)

Dealing with `ReadBarcode` in that context could mean:
 1. outright deprecate it (skeptical about that because there is performance benefit and it still seems to be a very - if not the most - popular use case?)
 2. have it return a `std::optional<Result>` (which would require an upgrade to c++17 also for any client code, which I think would be totally acceptable by now)
 3. model the 'not-found' `Result` as `format() == BarcodeFormat::None` instead of `status() == DecodeStatus::NotFound`. Note: the `bool isValid()` should stay and behave exactly like before (check for error and non-emptyness).

EDIT: I welcome any feedback as usual.

**Comment by vkrause** [comment]
We are on C++17 anyway, so I don't see anything in here that would be a problem for us.

**Comment by axxel** [comment]
Just pushed something semi-finished before I'm off over the weekend to enable you all to take a look and comment.

**Comment by axxel** [comment]
The error stuff stays as is and I decided against the std::optional idea which is not clearly superior and would introduce too much hassle for my taste a.t.m. I might change the `Result` internals to use a Qt-style `d`-pointer to a private struct and then an 'empty' result is just a null pointer.
