### ISSUE TITLE
Fatal error C1083: Can not open include file: “BitArray.h”: No such file or directory

### ISSUE THREAD

**Issue by UnknownObject000** [nu-book/zxing-cpp#347]
I got this error ```F:\vcpkg\installed\x64-windows\include\ZXing\oned\ODRowReader.h(20,10): fatal error C1083: Can not open include file: “BitArray.h”: No such file or directory``` when I included any reader file under ```ZXing/OneD```.
My Enviroument:
```
OS: Windows 11
IDE: Visual Studio 2022
ZXing library: 1.3.0 Installed with vcpkg
```

Shortest code to raise the error:
```c++
#include <ZXing/oned/ODRowReader.h>

int main()
{
	return 0;
}
```

**Comment by axxel** [comment]
You could probably solve the issue by making sure <ZXing> is in your include path. That said: In the next release this will not work anymore. The only remaining API to get access to the reader functionality will be via the `ReadBarcode.h` header. So please update your code to use that API only.

**Comment by axxel** [comment]
I'm about to make the next release. If you still have issues with this, now would be a good time to let me know while I can still fix things. If not, please close this issue.
