### ISSUE TITLE
When will the version be released officially?

### ISSUE THREAD

**Issue by DerrickChina** [nu-book/zxing-cpp#35]

**Comment by huycn** [comment]
Hi DerrickChina,

By "officially", do you mean binary release?
If yes, the answer is no binary release is planned. The project is self-contained, and it's very easy to "embed" into your own project, thus we think binary releases is not necessary.

That being said, there is one release available on nuget for WinRT:  https://www.nuget.org/packages/huycn.zxingcpp.winrt but the version is a bit dated with only reader included. We are going probably make an update soon.

**Comment by DerrickChina** [comment]
Hi huycn,
I'm sorry to mislead you. My meaning is not the binary release, code release is enough to me.
I suggest you team could do code release if you think the release is stable.

**Comment by huycn** [comment]
That is not bad idea. I will look into it after fixing the issue where the black box tests seem to be platform dependent. Thanks!

**Comment by simonschmeisser** [comment]
It would be great it this had a version number and official release (tagged source code). Everything else can then be worked out by linux distributions

**Comment by huycn** [comment]
Release created. Thank @DerrickChina and @simonschmeisser for suggestion!
