### ISSUE TITLE
One barcode is recognized as two with different bounding box

### ISSUE THREAD

**Issue by haibara502** [nu-book/zxing-cpp#350]
![4](https://user-images.githubusercontent.com/4556808/177078940-8763f305-1b15-4617-bae7-9a8bf1822701.png)
The image above is recognized as two barcodes with different bounding boxes.
[13,9,281,9,281,216,13,216], [13,217,281,217,281,243,13,243]

**Comment by duanqn** [comment]
Image source: https://github.com/zxing/zxing/blob/master/core/src/test/resources/blackbox/code39-1/4.png

**Comment by duanqn** [comment]
We were testing on v1.3.0 (50f53ef)

**Comment by duanqn** [comment]
ZXing-cpp results visualized as blue boxes.
![4_visualize](https://user-images.githubusercontent.com/21275667/177099991-77b79fa2-2bf4-4617-9278-d71c83b1390c.png)
