### ISSUE TITLE
Android  app couldn't scan PDF417 Code when tryRotate is true and horizontal android device screen

### ISSUE THREAD

**Issue by bestpower** [nu-book/zxing-cpp#353]
Commit ID: 53a5d670202750d717fae846f5e01dd464bbcba8
Android project path: zxing-cpp/tree/master/wrappers/android
Compile System OS: Windows 10
IDE: android-studio-2021.2.1.15-windows
NDK: 21.4.7075529

Recurrence steps:
1.Clone git project
2.Import wrappers/android project into android studio ide
3.Sync and Compile android project with as ide
4.Install apk into android device
5.Run ZXingCpp-Demo App
6.Click tryRotate button and scan some barcode photos
7.Observe output info on the app UI

Bug phenomenon info:
When take the PDF417 barcode photo and scan, I have found it couldn't output san result when take horizontal android device screen to scan, but it could output san result when take vertical android device screen to scan.
In addition, other code types no exist this bug.
Please help analysis and solve this bug, thank you.

**Comment by duanqn** [comment]
See #349 , I think PDF417 currently does not support tryRotate.
Would be nice to see a fix soon.
