### ISSUE TITLE
Access intermediate results

### ISSUE THREAD

**Issue by duanqn** [nu-book/zxing-cpp#358]
Hi,
I would like to get some intermediate results of ZXing-cpp so that when some barcodes are not recognized as expected, I can debug them by myself.
For example, it may be useful to get the binarized image and the detected "patterns" on the binarized image.
I noticed that ZXing-cpp currently does not expose these internal results. I previously used a hack to include non-published header files under individual barcode format folders but it's now broken with the latest code changes. Can we consider adding a supported way to extract some intermediate results? I'd be happy to help if there's some coding work.

**Comment by axxel** [comment]
I will not add debugging related functionality to the public API. I'm trying hard to limit and minimize that API without breaking (too much) client side code. Adding new stuff that is not required in normal operation but would then have to be kept maintained would be contrary to that goal.

I suggest you don't work with the "installed" library but instead with the git sources directly and add your hacks there. In fact, what ever you have should still work there as I only removed all the "internal" headers from the installation set, which was actually a change request (#168) and allows for further cleanup and improvements down the road. See e.g. @gitlost [branch](https://github.com/gitlost/zxing-cpp/tree/diagnostics2) with lots of debugging related changes that he felt the need to add.

I'd also like to point to the `PRINT_DEBUG` macro and the `LogMatrix` support code that I use for debugging the library. If you have some changes that would extend these features (and not be too invasive) and are also hidden behind the `PRINT_DEBUG` or other macro, please provide a PR and I'll have a look.

**Comment by duanqn** [comment]
Thanks. I'm closing this issue now as I don't have any immediate contribution ready.
