### ISSUE TITLE
Invalid Position for a barcode when image is rotated 180 degrees

### ISSUE THREAD

**Issue by mbaros100** [nu-book/zxing-cpp#360]
![a](https://user-images.githubusercontent.com/8537079/180050282-39f4300a-1b40-4593-b0ad-5704ba3aa1b2.png)

For this image when importing the positions and highlighting bounding boxes,  you can see the one for PDF417 format is placed incorrectly in the bottom-left corner instead of the top-right
<img width="363" alt="highlight" src="https://user-images.githubusercontent.com/8537079/180050854-90ff8e79-a132-4699-a0ab-568e05208819.png">

**Comment by axxel** [comment]
What version of the library are you using? I just checked with the current HEAD revision and all symbols are located correctly. I just recently added 90° rotation support for PDF417 and thereby might have "accidentally" fixed the problem that you just discovered.

**Comment by mbaros100** [comment]
I am using the 1.3.0 release. I will check the latest versions and as you suggested, this might be fixed. thanks a lot for the reply
