### ISSUE TITLE
Accuracy evaluation against v1.3.0 on a public QRCode dataset reveals accuracy regression

### ISSUE THREAD

**Issue by duanqn** [nu-book/zxing-cpp#370]
## Environment
Ubuntu 20.04
GCC 10.3.0
Ninja 1.10.0
CMake options: `-DBUILD_WRITERS=OFF -DBUILD_BLACKBOX_TESTS=ON -DBUILD_EXAMPLES=OFF`

## Dataset
https://boofcv.org/notwiki/regression/fiducial/qrcodes_v3.zip
Use 'Detection' part.

## Runtime Configuration
Downscale Factor = 2
Downscale Threshold = 200

## Accuracy Overview
Note: The dataset has labelled 1232 QR codes in total. All numbers below refer to the number of barcodes, not the images.
Since the dataset does not have labels for other barcode formats, they may appear as "insert" errors.

**v1.3.0** 
Correct: 674
Missed: 558
Insert: 3
detection - blurred: 35 / 65 (53.85% correct)
detection - bright_spots: 40 / 97 (41.24% correct)
detection - brightness: 63 / 85 (74.12% correct)
detection - close: 40 / 40 (100.0% correct)
detection - curved: 32 / 60 (53.33% correct)
detection - damaged: 15 / 43 (34.88% correct)
detection - glare: 18 / 53 (33.96% correct)
detection - high_version: 2 / 37 (5.41% correct)
detection - lots: 150 / 420 (35.71% correct)
detection - monitor: 17 / 17 (100.0% correct)
detection - nominal: 64 / 78 (82.05% correct)
detection - noncompliant: 21 / 26 (80.77% correct)
detection - pathological: 9 / 23 (39.13% correct)
detection - perspective: 24 / 35 (68.57% correct)
detection - rotations: 126 / 133 (94.74% correct)
detection - shadows: 18 / 20 (90.0% correct)

**latest** (e0b55812e8403d591339f89ddffbd16db4)
Correct: 530
Missed: 702
Insert: 3
detection - blurred: 35 / 65 (53.85% correct)
detection - bright_spots: 40 / 97 (41.24% correct)
detection - brightness: 63 / 85 (74.12% correct)
detection - close: 40 / 40 (100.0% correct)
detection - curved: 32 / 60 (53.33% correct)
detection - damaged: 12 / 43 (27.91% correct)
detection - glare: 18 / 53 (33.96% correct)
detection - high_version: 2 / 37 (5.41% correct)
**detection - lots: 10 / 420 (2.38% correct)**
detection - monitor: 17 / 17 (100.0% correct)
detection - nominal: 64 / 78 (82.05% correct)
detection - noncompliant: 21 / 26 (80.77% correct)
detection - pathological: 8 / 23 (34.78% correct)
detection - perspective: 23 / 35 (65.71% correct)
detection - rotations: 127 / 133 (95.49% correct)
detection - shadows: 18 / 20 (90.0% correct)

## Improvement cases
qrcodes_v3/qrcodes/detection/rotations/image029.jpg

## Regression cases
qrcodes_v3/qrcodes/detection/perspective/image012.jpg
qrcodes_v3/qrcodes/detection/damaged/image006.jpg
qrcodes_v3/qrcodes/detection/damaged/image005.jpg
qrcodes_v3/qrcodes/detection/damaged/image003.jpg
qrcodes_v3/qrcodes/detection/lots/image006.jpg
qrcodes_v3/qrcodes/detection/lots/image002.jpg
qrcodes_v3/qrcodes/detection/lots/image004.jpg
qrcodes_v3/qrcodes/detection/lots/image005.jpg
qrcodes_v3/qrcodes/detection/lots/image003.jpg
qrcodes_v3/qrcodes/detection/lots/image001.jpg
qrcodes_v3/qrcodes/detection/lots/image007.jpg
qrcodes_v3/qrcodes/detection/pathological/image023.png

**Comment by duanqn** [comment]
@axxel Can you take a look at the regression cases? Most of them are from the "lots" category.

For example, v1.3.0 can detect some of the QR codes in this image.
![image001_visualize](https://user-images.githubusercontent.com/21275667/183037392-c576ca9d-8de1-4565-8b2a-dc87b2013fc9.jpg)

... but the latest version missed most of them.
![image001_visualize](https://user-images.githubusercontent.com/21275667/183037426-e53eea59-7d05-441a-be22-4ae9efe38d54.jpg)

Is this due to recent changes, or am I using it wrong?

**Comment by axxel** [comment]
Thanks for bringing this to my attention including the complete statistics. If you want to help fixing this you could bisect the changes and find out which exact changeset between 1.3 and 1.4 caused this regression.

**Comment by duanqn** [comment]
It seems one of the commits causing this problem is 7f306d287a03bf1b2a389a5f1e46c5f2f49bb349. I'm double-checking to see if there is more.

**Comment by axxel** [comment]
My latest changes should bring the 'lots' results close to 100%.
