### ISSUE TITLE
Include error for ZXing/qrcode/QREncodeResult.h

### ISSUE THREAD

**Issue by french-paragon** [nu-book/zxing-cpp#372]
Hi, I am trying to generate a vector QR code and as such I wanted to use the encoder.

I had to include <ZXing/qrcode/QREncodeResult.h> and <ZXing/qrcode/QREncoder.h>, but there is a problem with the file <ZXing/qrcode/QREncodeResult.h>.

Namely, the includes in the .h file are absolute while they should, in theory, be relative to be usable outside of the project itself. This is :

#include "ByteArray.h"
#include "ByteMatrix.h"
#include "QRCodecMode.h"
#include "QRVersion.h"

should be

#include "../ByteArray.h"
#include "../ByteMatrix.h"
#include "./QRCodecMode.h"
#include "./QRVersion.h"

I am not certain if the maintainer would agree, but I can prepare a patch to solve all these errors in the code, this is not that hard.

**Comment by axxel** [comment]
I don't know what you mean by "vector QR code" but please note that you should only use the `MultiFormatWriter.h` API. The rest should be considered internal and will disappear, see also #332.

**Comment by french-paragon** [comment]
Vector as opposed to bitmap. I need to generate a vector QR code and export it in pdf.

If I am not mistaken, MultiFormatWriter gives an bitmap, isn't it ?

**Comment by french-paragon** [comment]
Ha, neverming, the qr code writer do not account for the width and height arguments in MultiFormatWriter. Sorry about that, but I managed

**Comment by axxel** [comment]
I meant to point you to https://github.com/nu-book/zxing-cpp/blob/f187e3e6fba80ea0ee97713aa3c165a26b30e062/core/src/BitMatrixIO.cpp#L35 for an idea on how to possibly generate a PDF from the `BitMatrix`, but I was too slow, it seems. ;)
