### ISSUE TITLE
Inaccurate Position for detected barcode

### ISSUE THREAD

**Issue by mbaros100** [nu-book/zxing-cpp#379]
![k](https://user-images.githubusercontent.com/8537079/183986498-bf0c3646-bca7-43bd-a499-dfff78d3f727.jpg)

Bounding box (position) is inaccurate:

{54,10}  {407,10}  {407,11}  {54,11}

it is only 2 lines on top of the barcode

**Comment by axxel** [comment]
It is accurate. That are the only two lines that contain a valid EAN-13 symbol. For the rest of the symbol the while lines between the black ones are too small.

**Comment by mbaros100** [comment]
![a](https://user-images.githubusercontent.com/8537079/185633017-ba4fad41-b262-4578-87f3-d33711c90805.jpg)

This is how the Java version recognized the current barcode

**Comment by axxel** [comment]
Thanks for pointing out that the Java version is working better here. There is still nothing I can do for you from inside zxing-cpp, though.
