### ISSUE TITLE
Compile error on centos7

### ISSUE THREAD

**Issue by DerrickChina** [nu-book/zxing-cpp#38]
# Build Step:
 cd wrappers/winrt
 cmake .
 make

# Build Errors:
## 1. leak c++11 options
* ===========================================
[  1%] Building CXX object ZXingCore/CMakeFiles/ZXingCore.dir/src/BarcodeFormat.cpp.o
In file included from /usr/include/c++/4.8.2/type_traits:35:0,
                 from /root/ZXing/zxing-cpp-master/core/src/BarcodeFormat.cpp:21:
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
===========================================
solution:
add following option to the CMakelist.txt
===========================================
add_compile_options(-std=c++11)
===========================================

## 2. leak std::vector member function

* ===========================================
/root/ZXing/zxing-cpp-master/core/src/Result.cpp: In member function ‘void ZXing::Result::addResultPoints(const std::vector<ZXing::ResultPoint>&)’:
/root/ZXing/zxing-cpp-master/core/src/Result.cpp:61:73: error: no matching function for call to ‘std::vector<ZXing::ResultPoint>::insert(std::vector<ZXing::ResultPoint>::const_iterator, std::vector<ZXing::ResultPoint>::const_iterator, std::vector<ZXing::ResultPoint>::const_iterator)’
  _resultPoints.insert(resultPoints().end(), points.begin(), points.end());
                                                                         ^
/root/ZXing/zxing-cpp-master/core/src/Result.cpp:61:73: note: candidates are:
In file included from /usr/include/c++/4.8.2/vector:69:0,
                 from /root/ZXing/zxing-cpp-master/core/src/ByteArray.h:18,
                 from /root/ZXing/zxing-cpp-master/core/src/Result.h:19,
                 from /root/ZXing/zxing-cpp-master/core/src/Result.cpp:18:
/usr/include/c++/4.8.2/bits/vector.tcc:107:5: note: std::vector<_Tp, _Alloc>::iterator std::vector<_Tp, _Alloc>::insert(std::vector<_Tp, _Alloc>::iterator, const value_type&) [with _Tp = ZXing::ResultPoint; _Alloc = std::allocator<ZXing::ResultPoint>; std::vector<_Tp, _Alloc>::iterator = __gnu_cxx::__normal_iterator<ZXing::ResultPoint*, std::vector<ZXing::ResultPoint> >; typename std::_Vector_base<_Tp, _Alloc>::pointer = ZXing::ResultPoint*; std::vector<_Tp, _Alloc>::value_type = ZXing::ResultPoint]
     vector<_Tp, _Alloc>::
     ^
/usr/include/c++/4.8.2/bits/vector.tcc:107:5: note:   candidate expects 2 arguments, 3 provided
===========================================
Solution:
replace with other member function:
zxing-cpp-master/core/src/Result.cpp:61
===========================================
void
Result::addResultPoints(const std::vector<ResultPoint>& points)
{
        for (size_t i = 0; i < points.size(); ++i)
        {
                _resultPoints.push_back(points[i]);
        }
        //_resultPoints.insert(resultPoints().end(), points.begin(), points.end());
}
===========================================

## 3. Unable to visit the protected member function:
* ===========================================
[ 37%] Building CXX object ZXingCore/CMakeFiles/ZXingCore.dir/src/oned/ODUPCEANReader.cpp.o
In file included from /root/ZXing/zxing-cpp-master/core/src/oned/ODUPCEANReader.h:19:0,
                 from /root/ZXing/zxing-cpp-master/core/src/oned/ODUPCEANReader.cpp:18:
/root/ZXing/zxing-cpp-master/core/src/oned/ODRowReader.h: In lambda function:
/root/ZXing/zxing-cpp-master/core/src/oned/ODRowReader.h:184:15: error: ‘static float ZXing::OneD::RowReader::PatternMatchVariance(const int*, const int*, size_t, float)’ is protected
  static float PatternMatchVariance(const int *counters, const int* pattern, size_t length, float maxIndividualVariance);
               ^
/root/ZXing/zxing-cpp-master/core/src/oned/ODUPCEANReader.cpp:58:100: error: within this context
    return RowReader::PatternMatchVariance(counters.data(), pattern, length, MAX_INDIVIDUAL_VARIANCE) < MAX_AVG_VARIANCE;
                                                                                                    ^
make[2]: *** [ZXingCore/CMakeFiles/ZXingCore.dir/src/oned/ODUPCEANReader.cpp.o] Error 1
make[1]: *** [ZXingCore/CMakeFiles/ZXingCore.dir/all] Error 2
make: *** [all] Error 2
===========================================
Solution:
change protected to public(comment the key word "protected")
/root/ZXing/zxing-cpp-master/core/src/oned/ODRowReader.h：183
===========================================
//protected:
        static float PatternMatchVariance(const int *counters, const int* pattern, size_t length, float maxIndividualVariance);
===========================================

## 4. Demo depend on the windows api
* ===========================================
[ 98%] Building CXX object CMakeFiles/ZXingWinRT.dir/BarcodeReader.cpp.o
/root/ZXing/zxing-cpp-master/wrappers/winrt/BarcodeReader.cpp:26:17: fatal error: wrl.h: No such file or directory
 #include <wrl.h>
                 ^
compilation terminated.
===========================================

**Comment by huycn** [comment]
Hi,
winrt wrapper is to build WinRT component or Windows Store app only. It will not work on Linux.
I just added instructions to use library on platforms where no wrapper is provided. You may want to check it out.

**Comment by DerrickChina** [comment]
I understand, close the case..
