### ISSUE TITLE
Failed to build shared libs because libzueci is static

### ISSUE THREAD

**Issue by duanqn** [nu-book/zxing-cpp#382]
```
_deps/zueci-build/libzueci-static.a(zueci.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
```
It seems zueci is not compiled with position-independent code enabled, which then caused the ZXing-cpp shared lib to fail. Any suggestions on how to solve this?

**Comment by duanqn** [comment]
On commit 50f53ef73f610788feaebd4159f8e4b32e6d38d8

**Comment by duanqn** [comment]
https://github.com/nu-book/zxing-cpp/blob/master/core/CMakeLists.txt
Here in line 444, target_link_libraries is set to `zueci-static`. Can we solve the issue by linking with the dynamic lib here?

**Comment by axxel** [comment]
Could you please try to add the line
```
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
```
next to the `set(ZUECI_STATIC ON CACHE INTERNAL "")` in `core/CMakeLists.txt`?
