### ISSUE TITLE
Problem (and solution?) reading DataBarExpanded

### ISSUE THREAD

**Issue by mholst78** [nu-book/zxing-cpp#384]
Hello, 
First of all thank you for your great library! We are using it for years now and are really happy with it.

When we tried to use the recent version we found that one of our test codes could not be read any longer. It is a DataBarExtended with the content "(01)00000000000000".
I debugged it down to the function "DecodeAI01AndOtherAIs". When I removed the lines

149: if (trailer.empty())
150:     return {};

the result was as expected and like in 1.3.0. 
For debugging: The BitArray of the calling function "DecodeExpandedBits" contained 48 bits with only bits at index 1 and 2 set to 1. 
I'm not sure if this is a bug or if our code is really not valid.

**Comment by axxel** [comment]
Could you provide a sample image with the problematic symbol?

**Comment by mholst78** [comment]
Sure, here it is:

![Code image before decoding](https://user-images.githubusercontent.com/111492159/185407132-01e6ae0e-9440-4b35-87a8-70e542d4cb92.png)

**Comment by axxel** [comment]
Thanks for your input. After consulting the spec I came to the conclusion that an empty "trailer" variable is perfectly within the spec.

**Comment by mholst78** [comment]
Thank you for fixing this!
