### ISSUE TITLE
how to build a dynamic library for zxing-cpp from source (on Linux)

### ISSUE THREAD

**Issue by FelixSchwarz** [nu-book/zxing-cpp#42]
Probably I'm just stupid but I can not get zxing-cpp to build a dynamic library (always getting a statically linked "libZXingCore.a").

I'm using the latest zxing-cpp (afb763ee2409eb2753aeec03488fa723205a3fcc), g++ 8.1.1, cmake 3.11.2 on Fedora 28.

As I did not find specific build instructions I just ran `cmake core && make`.

**Comment by axxel** [comment]
The `CMakeLists.txt` currently simply has no build target for a shared library. You could simply add the string `SHARED` at the end of the `add_library (ZXingCore` line. cmake will produce an so then. If that works for you just like that. Let us know and we might add a proper target for it.

Grüße aus Berlin :)

**Comment by FelixSchwarz** [comment]
That worked. Thank you very much for your help.

However I did not really use the shared library: In the meantime somehow I managed to fix my issues in the current code (which uses another library). That means I don't get to spend time on zxing-cpp (even though I like this library).

What would have helped me is a basic CLI tool (just to check which barcodes this code can recognize) and a way to install it as a shared library (so I can build a Python wrapper with pybind11).

**Comment by antonio-rojas** [comment]
So, any hope to have a shared library target? From a packager point of view that would be really convenient.

**Comment by huycn** [comment]
@antonio-rojas I've just added support for building shared library. To do so, you can pass BUILD_SHARED_LIBRARY to cmake on command line, for example:
```
cmake -DBUILD_SHARED_LIBRARY=true -DCMAKE_BUILD_TYPE=Release ../zxing-cpp
```

**Comment by antonio-rojas** [comment]
awesome, thanks!
