### ISSUE TITLE
Blackbox generic runner to not use boost::filesystem

### ISSUE THREAD

**Issue by huycn** [nu-book/zxing-cpp#47]
Currently boost::filesystem is only used to discover *.png files in test/blackbox. We can use dirent.h on POSIX platform instead. It will be easy to replace and this will simplify build process.

**Comment by axxel** [comment]
That should surely be doable and remove the dependency but I'd argue, it is somehow the 'wrong direction' and would suggest another approach: recent gcc and clang on Linux/macOS support c++17's std::filesystem out of the box and for the 'general' public / library user, there is no need to build the test-runner at all, anyway? So how about making sure the cmake setup treats boost/std::filesystem as optional, so those people will not need boost. Library developers should have no problem providing a recent compiler or boost.

**Comment by huycn** [comment]
I came across this issue as I was trying to build generic test runner with mingw on my Windows. Looking for a binary distribution of boost was not that trivial. Using c++17 std::filesystem is a good idea indeed. With lodepng, we could have only one version of blackbox test runner. I was concerned with the support of old compiler, but you're right, general public doesn't need to run theses tests at all.

**Comment by huycn** [comment]
I replace boost::filesystem with std::filesystem or std::experimental::filesystem if either is present, and fallback to dirent.h if none.
