### ISSUE TITLE
Request for CLI

### ISSUE THREAD

**Issue by workflowsguy** [nu-book/zxing-cpp#48]
It would be great to have a command line interface included in the project.
I have been looking high and low for a command line tool that is actually able to reliably detect various barcodes in images.

E.g. `zbarimg` 0.10 CLI is not able to detect all QR Codes that e.g. the iPhone camera app recognises, and the CLI provided with [https://github.com/glassechidna/zxing-cpp](https://github.com/glassechidna/zxing-cpp) is not able to detect the QR codes zbarimg recognizes... :frowning_face:

**Comment by huycn** [comment]
I added example programs for barcode scanning (scan_png), you may want to check it out in 'example' folder. If it still fail to detect, you can post your images here as a new issue so that we will have a look.

**Comment by workflowsguy** [comment]
@huycn I will gladly provide examples for potentially non-detected codes.
However, I am not sure how to correctly build the various libraries & programs on OS X, being unfamiliar with `cmake`.

I seem to have successfully build `scan_png`, but I just want to rule out the possibility of reporting false non-detections that result from incorrectly built programs.

So I would appreciate some guidelines on how to build the individual `zxing-cpp` parts.

**Comment by huycn** [comment]
CMake config allows you to disable all readers or all writers, but not particular one. Thus, if you get `scan_png` executable, all supported readers are included. Furthermore, there is no build config that will change reader's behavior (unless it's a big of course). You may tune reader's behavior with `DecodeHints` passed to `MultiFormatReader`. Two options that touch QR Code are: `tryHarder`, which is already enabled by default in `scan_png`, and `charset` which is left unset, but it will affect only text conversion not detection.

**Comment by workflowsguy** [comment]
OK, I will test with `scan_png` then.
Thanks!

**Comment by omnigenous** [comment]
As of today `scan_png` is no longer present. Use `ZXingReader` instead https://github.com/zxing-cpp/zxing-cpp/blob/v2.2.1/example/ZXingReader.cpp

**Comment by agguser** [comment]
For convenience to users, a CLI binary should be provided in the package, to not need to create it themselves, e.g. with:
```(sh)
curl -s -S https://raw.githubusercontent.com/zxing-cpp/zxing-cpp/refs/tags/v2.3.0/example/ZXingReader.cpp |
   g++ -Wall -I/usr/include/ZXing -I/usr/include/stb -lZXing -o ~/bin/zxing_reader -xc++ -
```

**Comment by axxel** [comment]
> For convenience to users, a CLI binary should be provided in the package, to not need to create it themselves

What do you mean with "in the package"? Are you suggesting to include a binary in the sources tgz/zip file?

**Comment by agguser** [comment]
I meant that a command-line program should be included, so that  when `zxing-cpp` package is installed, they will also get a CLI binary (e.g. zxing_reader), in addition to headers (\*.h) and libraries (\*.so).

**Comment by axxel** [comment]
What "package" are you talking about? Note: there are [quite a few](https://repology.org/project/zxing-cpp/versions) packages out there.

**Comment by agguser** [comment]
Arch Linux `zxing-cpp` package.

**Comment by axxel** [comment]
> [Arch Linux `zxing-cpp`](https://archlinux.org/packages/extra/x86_64/zxing-cpp/) package.

What is or is not included in that package is at the sole discretion of its maintainer @antonio-rojas.
