### ISSUE TITLE
#define ZXING_VERSION_MAJOR...

### ISSUE THREAD

**Issue by hondero2552** [nu-book/zxing-cpp#55]
#define ZXING_VERSION_MAJOR  1
#define ZXING_VERSION_MINOR  0
#define ZXING_VERSION_PATCH  3

This would be extremely helpful. For more than obvious reasons I think. I can do it. I just want to make sure everyone is on board.

PS: Maybe in the "ZXConfig.h" file?

**Comment by huycn** [comment]
ZXConfig.h is good me.
