### ISSUE TITLE
Interleaved 2 of 5 with bearer bar not recognised

### ISSUE THREAD

**Issue by GregoryVV** [nu-book/zxing-cpp#57]
Recognition of interleaved 2 of 5 codes with a bearer bar fails when the second END_PATTERN_REVERSED is used (this will be the case when the barcode's wide to narrow ratio is 3).
After some debugging I found that when searching the end pattern the calculation of the narrow line width is wrong in this case because the length of the pattern is 5 in this case and not 4.
I managed to fix the issue by replacing line 159 in ODITFReader.cpp:

```
int narrowLineWidth = (end - begin) / 4;
```

by the following:

```
int patternLength = 0;
for( int i = 0; i < pattern.size(); ++i )
{
	patternLength += pattern[ i ];
}
int narrowLineWidth = (end - begin) / patternLength;
```

**Comment by axxel** [comment]
Thanks for spotting and debugging this!
