### ISSUE TITLE
How to use it to deal with a  jpeg/bmp/....  picture ?

### ISSUE THREAD

**Issue by falcontr14** [nu-book/zxing-cpp#59]

**Comment by axxel** [comment]
Please see https://github.com/nu-book/zxing-cpp#to-read-barcodes and also look at https://github.com/nu-book/zxing-cpp/blob/743ebade2af7902e1411e4664a01c2d1035fbc19/example/scan_png.cpp#L134-L137 as an example on how to feed your image data into the library.

**Comment by axxel** [comment]
Quick update: the [scan_image.cpp](https://github.com/nu-book/zxing-cpp/blob/master/example/scan_image.cpp) example now supports png/jpeg/bmp directly. This should definitively answer your question (in case it was still open).
