### ISSUE TITLE
.wasm usage with Webpack

### ISSUE THREAD

**Issue by jtraulle** [nu-book/zxing-cpp#60]
Hello there,

Thank you for this port of ZXing :wink: 
I am trying to use the wasm target with Webpack but cannot get it to work.

I do not know much about wasm and emscripten but I am also using opencv.js that uses also emscripten and their emscripten built file only require one JS file as the wasm binary is embedded into that .js file. With this output, it works like a charm when used with Webpack.

You can see their output here : [opencv.js.txt](https://github.com/nu-book/zxing-cpp/files/2948410/opencv.js.txt) with var wasmBinaryFile.

Also, I think a less generic export than Module would be better. What about using ZXing instead ?

Do you have any idea how to get a similar build as OpenCV (only one JS file with embedded wasm binary) using emscripten ?

Thanks !

**Comment by jtraulle** [comment]
I slightly edited my original message because the example link included was wrong (asm.js instead of wasm implementation). I uploaded a compiled version with wasmBinaryFile bundled inside (build from opencv sources) so you can see.

**Comment by jtraulle** [comment]
I have tweaked the `CMakeLists.txt` file and changed the last line to this :

```cmake
set (CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} --bind -Oz -s DISABLE_EXCEPTION_CATCHING=0 -s FILESYSTEM=0 -s WASM=1 -s MODULARIZE=1 -s SINGLE_FILE=1 -s EXPORT_NAME=\"'zxing'\"")
```

So basically, I request a self-contained .js file that embeds the wasm binary, specify a custom export name and enable modularization.

In my javascript file, I import my file like this
```js
import zxing from "zxing-js/zxing_reader.js";
```

where `zxing_reader.js` is the file generated by `emscripten`.

Next in my code, I call it like explained in ```demo_reader.html``` but with my new export name (zxing)
```js
var buffer = zxing._malloc(imageData.length);
zxing.HEAPU8.set(imageData.data, buffer);
var result = zxing.readBarcodeFromPng(buffer, imageData.length, true, 'QR_CODE');
zxing._free(buffer);
```
but when I try to execute, I get an error stating that _malloc is not a function.
```
TypeError: zxing_js_zxing_reader_js__WEBPACK_IMPORTED_MODULE_2___default.a._malloc is not a function
```
I tried to search about this error and found out that functions should be added in EXPORTED_FUNCTIONS, so I re-tried with
```cmake
set (CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} --bind -Oz -s DISABLE_EXCEPTION_CATCHING=0 -s FILESYSTEM=0 -s WASM=1 -s MODULARIZE=1 -s SINGLE_FILE=1 -s EXPORTED_FUNCTIONS=\"['_malloc', '_free']\" -s EXPORT_NAME=\"'zxing'\"")
```
but it still does not work (got the same error).

I also tried to change optimization level to other values and it does not work even with `-O0`

I am really new to all this `emscripten` stuff so, if any of you have an idea, it would be really helpful :) @huycn ?

Thanks :)

**Comment by huycn** [comment]
Since you use `MODULARIZE=1` all the exported functions are put inside a function that will load asynchronously the wasm module, and you can get access to the module with a callback (as [documented here](https://emscripten.org/docs/getting_started/FAQ.html#how-can-i-tell-when-the-page-is-fully-loaded-and-it-is-safe-to-call-compiled-functions)):
```javascript
zxing().then(function (zxing) {
    var buffer = zxing._malloc(imageData.length);
    zxing.HEAPU8.set(imageData.data, buffer);
    var result = zxing.readBarcodeFromPng(buffer, imageData.length, true, 'QR_CODE');
    zxing._free(buffer);
}
```

Thank you for your suggestion to change module name to `ZXing` stead of `Module`. It's a good idea, I will definitely do that.

Note also that by put zxing.asm directly into .js, you increase the final file size but also loading time (although not much) since the binary is now saved as base64.

**Comment by jtraulle** [comment]
Great @huycn , thanks for the help and the explanation with the link to emscripten docs ! It works now 🙂
