### ISSUE TITLE
webcam demo

### ISSUE THREAD

**Issue by kousu** [nu-book/zxing-cpp#61]
I've adapted [jsQR's demo](https://cozmo.github.io/jsQR/) with [your demo](https://nu-book.github.io/zxing-cpp/demo_reader.html) to make this webcam-able demo:

Since it doesn't seem to be in the repo, in lieu of a PR here's a link to a gist:

https://gist.github.com/kousu/6ca604cb9441264a24e4d719ee68d2ee

**Comment by huycn** [comment]
Thank you, @kousu.
The reason you don't see in in repo is that these files are not in master branch, but gh-pages: https://github.com/nu-book/zxing-cpp/tree/gh-pages
