### ISSUE TITLE
[Q] Custom barcode zebra format

### ISSUE THREAD

**Issue by kashkashio** [nu-book/zxing-cpp#64]
Hello
I wonder if it's possible to create a custom barcode that will be unique to me?
can i create another format of my own using predefined symbols and spaces and line widths ?

let say i want to set that
e.g:
| || | ||| | = 1
|| || | | ||| = 2

and to be able to use zxing to read this custom barcode?

Thanks a lot

**Comment by axxel** [comment]
The answer to your question in the context of this c++ port is exactly the same as Sean Own gave you in the upstream Java project: you can implement your own barcode and use the infrastructure of the library but there is no built in support for defining a custom code. You may have a look at https://github.com/nu-book/zxing-cpp/blob/master/core/src/oned/ODITFReader.cpp for a relatively simple 1D code reader as a starting point.

**Comment by kashkashio** [comment]
Thank you very much
