### ISSUE TITLE
Expose more settings on the Windows Wrapper

### ISSUE THREAD

**Issue by William-Froelich** [nu-book/zxing-cpp#74]
It would be nice to expose more configurable hints for the Windows API wrapper. The big issue right now seems to be translating the enums properly.

I took a first-stab at it here :  https://github.com/William-Froelich/zxing-cpp/tree/Windows_Wrapper_API but I'd like to be able to incorporate this into the mainline if it's deemed valuable.

**Comment by huycn** [comment]
@William-Froelich I find your changes interesting. You can create a PR if you want, I will be pleased to merge it. Thanks!
