### ISSUE TITLE
No exported symbols in Windows

### ISSUE THREAD

**Issue by ultrablox** [nu-book/zxing-cpp#77]
When builded with cmake on windows
`cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_DEBUG_POSTFIX=d -DCMAKE_CXX_STANDARD=14 -DCMAKE_GENERATOR_PLATFORM=x64 ../
`
`
cmake --build . --config Debug
`
no .lib is generated, only .dll.

**Comment by huycn** [comment]
The reason is that on Windows, only entities flagged with `__declspec(dllexport)` will be exported into DLL. Currently, there is none, thus nothing is exported, hence no .lib is generated.

**Comment by ultrablox** [comment]
Yea, but are you sure that this is expected behavior? Without .lib dll becomes quite useless except redefining interface and manual dll loading in runtime .

**Comment by huycn** [comment]
You are right, it's useless for now. You cannot even do anything with the .dll as it's practically empty. We need to add `__declspec(dllexport)` to all public classes. I've added it to my todo list. It will be done soon enough.

**Comment by vinovenkat93** [comment]
Hi! Can you give me an estimate on when this might be completed? I plan to use the library as a shared lib on Windows and it would be great if this gets done. Thanks!

**Comment by huycn** [comment]
@ultrablox @vinovenkat93 I've found a simpler way with [WINDOWS_EXPORT_ALL_SYMBOLS](https://cmake.org/cmake/help/latest/prop_tgt/WINDOWS_EXPORT_ALL_SYMBOLS.html), thus I don't need to include ZXingDefs.h and add ZXING_API all over the headers. The downside is the flag will export more than necessary and clients using library without __declspec(dllimport). I judge this should not be a big issue but if it is, please report.

**Comment by vinovenkat93** [comment]
@huycn What a coincidence. I just found that too. I was going to suggest the same thing. It does export everything, but that works for me. Thanks.

**Comment by huycn** [comment]
Note that the fix with WINDOWS_EXPORT_ALL_SYMBOLS has been merged by #83
