### ISSUE TITLE
Nuget package version is out of date (1.0.3 vs 1.0.5)

### ISSUE THREAD

**Issue by William-Froelich** [nu-book/zxing-cpp#78]
The current release is of the project according to CMakeLists.txt is 1.0.5, but the ZXingWinRT.nuspec still shows as version 1.0.3

The impact here is that when generating a nuget package the wrong version number code will be used.

Depending on when and how this is being published to nuget.org, it may also result in failing to deploy the latest version of the library unless there's a manual step taken to update it before publishing.

**Comment by huycn** [comment]
@William-Froelich Currently the nuget package is manually built and published. I will configure the project to build and deploy package automatically on each release using AppVeyor.

**Comment by William-Froelich** [comment]
Ok, any chance of getting v1.0.4 and v1.0.5 published to nuget gallery? I didn't see them there

https://www.nuget.org/packages/huycn.zxingcpp.winrt/

Or is this not where zxing-cpp is being published to?

**Comment by William-Froelich** [comment]
Thanks!
