### ISSUE TITLE
build zxing in ubuntu, fatal error: windows.h: No such file or directory  #include <windows.h>fatal error: windows.h: No such file or directory  #include <windows.h>

### ISSUE THREAD

**Issue by a361251388** [nu-book/zxing-cpp#85]
problem: zxing-cpp/wrappers/gdiplus/GdiplusInit.h:17:10: fatal error: windows.h: No such file or directory
 #include <windows.h>
how to replace it

**Comment by axxel** [comment]
The gdiplus wrapper makes only sens on windows, so you can only built it there. What are you trying to achieve?

**Comment by a361251388** [comment]
i want to acheive that recognise  QR code which may have big angle x, y, z rotation, broken or defaced

**Comment by axxel** [comment]
Then you should start with the project in the example directory and see if the `scan_png` example can decode your images.
