### ISSUE TITLE
1D readers should not test for upside-down codes if tryRotate is false

### ISSUE THREAD

**Issue by axxel** [nu-book/zxing-cpp#87]
I'm currently falling down a rabbit hole after I fired up a profiler for fun ;). Apart from other changes that I'm about to push I'd like to propose a change in the default behavior of the 1D readers. It turns out that the time spent in false-positives-tests is by far dominated by the 1D decoders. If you are only interested in upright codes (by setting tryRotate to false), you should not have to pay for an implicit upside-down check, which is currently the case.

People who formerly relied on that behavior would have to specify `tryRotate = true` in the future. Any objections?

**Comment by huycn** [comment]
As I understand, the flag `tryRotate` is only to allow scan codes at 90 or 270 degrees. We should able to read 1D barcodes either from left to right or from right to left the same way as we should able to read QRCode in any angle, no matter the settings of the reader. As `tryRotate` is false by default, make it dependent on this flag would mean that the code no longer works out-of-the-box.

Also, as legacy matter, I would keep the same behavior as original ZXing code for theses flags, to avoid unnecessary surprises. If we really want to give control on this behavior, I would suggest to add a new flag?

**Comment by axxel** [comment]
I see. I personally don't have any stakes in the 1D code. My DM code respects this parameter though, i.e. if tryRotate is false, it will only detect upright (+/- 45°) codes. The QRCode reader does in fact not care about this flag because it can deal with any orientation without any extra cost to pay (not the case for the DMDetector). I thought the purpose of this flag is improved speed (same as the tryHarder one). The way it is implemented (in the 1D case) does not consistently leverage this possibility. A comment in the code suggests that this was not really a deliberate choice in the sense that the author decided he needs to deal with upside-down codes as good as with upright codes but more that he thought it was "cheep" to support 0° and 180° in one go. It is cheaper than 90° but not "free".

I see your point about legacy behavior but I don't understand why dealing with 180° is more important than 90°. If I have a phone and scan some 1D code on a book/package/can, I would assume the 0° orientation is way more likely than any of the other. That said, not my area of expertise...

Feel free to close this issue if my arguments are not convincing ;).

Disclamer: what helps _a lot_ more in terms of speed, is of course to preselect the relevant codes in the application and only scan for those.

**Comment by axxel** [comment]
Never mind... (see comment in ODReader.cpp).
