### ISSUE TITLE
Restructure 1D algorithms for potentially substantial performance gains

### ISSUE THREAD

**Issue by axxel** [nu-book/zxing-cpp#89]
After having spent some time with a profiler on the `ODReader`s and having [heard](https://github.com/nu-book/zxing-cpp/issues/81#issuecomment-513302104) that the performance of the library on an (unknown) phone platform is only around 1 fps (even after the recent improvements) - I'm wondering whether there was interest in some structural changes of the `ODReader` to make it (hopefully considerably) faster?

@huycn: Can you give me some numbers from your real-world mobile app (preferably from the current HEAD code)?
 1. image input size (maybe a typical sample image?)
 1. fps / decoding time for one frame
 1. list of enabled readers

Looking at where the time is spent overall in a 'check everything' `MultiFormatReader` setup, one realizes that the majority of time is spent on the 1D readers. And in them a considerable amount is spent on
 1. going through the bits and counting how many successive bits are of the same value
 2. going through the bits again to see if there is enough 'quite zone' in front of the current pattern

Point 2 is already bad but worse is that both are repeated for each and every `ODReader` on the same set of bits. I recently made that part faster but even better would obviously be to perform it once instead of up to 11 times.

This would require to rewrite the detection part. Apart from the question of whether I will actually find the time to do that, I wanted to make sure the resulting deviation from upstream is not something that would kill your interest in merging it right from the start.

As far as I can tell, the upstream project is pretty much dead and the occasional fix worth porting over is mostly in the nasty decoding side of the puzzle, not the detection. So nothing to worry about.

**Comment by huycn** [comment]
@axxel I don't have typical image sample as we use in our B2B software and the use-cases are quite different from one client to another. Thus, we enable all readers by default (and very likely our clients don't change default parameters). To improve FPS, we fix the scan area size to a maximum of 840x480 pixels. That is, if the camera provides an image of 2560x1600 px, we create an GenericLuminanceSource only with 840x480 px at the center. With that, we get an "acceptable" performance and the real fps depends mostly on the API we use to acquire video stream (and also on camera's itself, or driver?, as we notice that for the same app, the fps rate changes a lot of one device to another. On some, it can achieve more than 30fps, on another, no more than 10).

About rewrite detection part, I will be very happy to merge it :) We found ways to mitigate the performance issue, but not without trade-offs. As our "active zone" is a small box inside the viewable area, it still takes some patience to align the pattern inside the box, at the right distance and focus. Thus, if your changes can improve that, I think it will be game changer.

**Comment by pyxdroid** [comment]
@axxel 
In the restructured hints code is an error now.
file: zxing-cpp/core/src/MultiFormatReader.cpp
 
MultiFormatReader::MultiFormatReader(const DecodeHints& hints)
{
	bool tryHarder = hints.shouldTryHarder();
	//if (hints.hasNoFormat()) {
        // must be (the NOT is missing here)
        if (!hints.hasNoFormat()) {
		bool addOneDReader =
			hints.hasFormat(BarcodeFormat::UPC_A) ||

Greetings and thanks to all for distributing this library.

pyxdroid

**Comment by axxel** [comment]
@pyxdroid thanks for pointing that out. I fixed it. Since this regression has nothing to do with the issue #89, please simply open a new issue the next time ;).

**Comment by axxel** [comment]
See [here](https://github.com/nu-book/zxing-cpp/commit/5566db9885b6bf8d40de64c50db5d65d7a29d484) for an initial code drop showing what I had in mind. The next step is reimplementing the second group of codes (those with width ratios of 1:2:3:4), namely Code128, Code93 and UPC/EAN.

**Comment by axxel** [comment]
After more than a year of working on this and spending a ridiculous amount of hours on it, I finally call this effort complete. I hope that someone will actually benefit from it :).
