### ISSUE TITLE
linker error when compiling for macOS

### ISSUE THREAD

**Issue by JBBgameich** [nu-book/zxing-cpp#95]
```
[100%] Linking CXX shared library libZXingCore.dylib
Undefined symbols for architecture x86_64:
  "ZXing::BitArray::getSubArray(int, int, ZXing::BitArray&) const", referenced from:
      ZXing::BitWrapperBinarizer::getBlackRow(int, ZXing::BitArray&) const in BitWrapperBinarizer.cpp.o
      ZXing::BitWrapperBinarizer::getBlackMatrix() const in BitWrapperBinarizer.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Seems to be related to https://github.com/nu-book/zxing-cpp/commit/d57cbe2121bcc761474b0f605bdfe0fa1fec676a#diff-5e24ace5ae61d1188c8939ca8d326e92R282

**Comment by axxel** [comment]
Ups. Thanks for pointing that out. Can you confirm that it links if you comment out the `#define ZX_FAST_BIT_STORAGE` line from `ZXConfig.h`?

**Comment by axxel** [comment]
@huycn the `BitWrapperBinarizer` class contains the only code calling `BitArray::getSubArray` and the class itself it not used anywhere in the code base. It seems it is also not part of upstream (judged by the copyright comment from you). What was your intention when introducing this class and are you using it?

I would suggest to remove it from the code base.

**Comment by huycn** [comment]
@axxel I believe it was intended to use in unit test where we have already binary data. I should modify the test code that no longer use it. In any case, if it's not used, please feel free to remove it. Thanks!

**Comment by JBBgameich** [comment]
Thanks for fixing this so quickly :)

**Comment by axxel** [comment]
Well, I was working on the project anyway, and since I just recently introduced this regression, I shall also fix it ;).
