### ISSUE TITLE
Find out DecodeStatus (error codes) when decoding QrCodes

### ISSUE THREAD

**Issue by maurosanjo** [nu-book/zxing-cpp#96]
Is there a way to expose decoding info to find out what went wrong when a qrcode fails to be decoded? 

This can be helpful to be able to tell if the image had a QrCode that failed to read or if the image did not have any QrCode at all.

**Comment by axxel** [comment]
Please have a look at the discussion and referenced changes in #88. Does that answer you question?

**Comment by axxel** [comment]
Closing this for lack of feedback from the OP.
