### ISSUE TITLE
Using ConvertUPCEtoUPCA, compile error

### ISSUE THREAD

**Issue by enzo-simone** [nu-book/zxing-cpp#98]
Hello,
using MSVC I'm trying to use the function
ZXing::OneD::UPCEANCommon::ConvertUPCEtoUPCA 

defined in
ZXing/oned/ODUPCEANCommon.h

so in my project I included
#include <ZXing/oned/ODUPCEANCommon.h>

but the latter includes
#include "ODUPCEANReader.h"

which in turn includes
#include "oned/ODRowReader.h"

which fails because files "ODUPCEANReader.h" and "ODRowReader.h" are in the same directory.

Thank you.

**Comment by huycn** [comment]
It was indeed a mistake, to include folder in relative path.
I'm going to fix it.
