### ISSUE TITLE
Issue with MSVC iterator guard in DEBUG

### ISSUE THREAD

**Issue by enzo-simone** [nu-book/zxing-cpp#99]
Hello,
this is gonna be a debatable one as it deals with Microsoft specific environment, but let me expose.

Method `ZXing::BitArray::isRange` is defined as
`
	bool isRange(int start, int end, bool value) const {
		return std::all_of(&_bits[start], &_bits[end], [value](uint8_t v) { return v == static_cast<int>(value); });
	}
`
but accessing `_bits[end]`, i.e. past the end, triggers an assertion just during debugging **though is perfectly legitimate to get its address since &_bits[end] == &_bits[0] + end**.

A solution could be 
`return std::all_of(std::begin(bits) + start, std::begin(bits) + end, [value](uint8_t v) { return v == static_cast<int>(value); });`

Thank you.

**Comment by axxel** [comment]
I'm not a MSVC user but it seems to be a valid point to me. Care to prepare a pull request?
